---
- :data:
    :name: Video
    :type: object
    :content_type: entity
    :boost: 10.0
    :api:
      :type: VideoObject
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :caption:
        :label: Alt-Label
        :type: string
        :storage_location: translated_value
        :search: true
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :content_url:
        :label: Bild URL
        :type: string
        :storage_location: value
        :validations:
          :format: url
      :thumbnail_url:
        :label: Thumbnail URL
        :type: string
        :storage_location: value
        :validations:
          :format: url
      :url:
        :label: Inhalt URL
        :type: string
        :storage_location: value
        :validations:
          :format: url
        :api:
          :name: sameAs
      :image:
        :label: Teaserbild
        :type: string
        :storage_location: value
        :validations:
          :format: url
        :ui:
          :show:
            :type: preview_image
      :youtube_url:
        :label: YouTube URL
        :type: string
        :storage_location: value
        :validations:
          :format: url
      :license:
        :label: Copyright / Lizenz
        :type: string
        :storage_location: value
        :search: true
      :content_location:
        :label: Ort
        :type: linked
        :linked_table: places
        :template_name: Örtlichkeit
      :width:
        :label: Breite
        :type: number
        :storage_location: value
        :validations:
          :format: integer
      :height:
        :label: Höhe
        :type: number
        :storage_location: value
        :validations:
          :format: integer
      :content_size:
        :label: Dateigröße
        :type: number
        :storage_location: value
        :validations:
          :format: integer
      :file_format:
        :label: Dateiformat
        :type: string
        :storage_location: value
      :duration:
        :label: Länge
        :type: string
        :storage_location: value
      :director:
        :label: Regie
        :type: linked
        :linked_table: persons
        :template_name: Person
      :contributor:
        :label: Kamera
        :type: linked
        :linked_table: persons
        :template_name: Person
      :tags:
        :type: mixin
        :name: tags
      :media_archive:
        :type: mixin
        :name: media_archive
      :media_archive_categories:
        :type: mixin
        :name: media_archive_categories
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Video"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
