---
- :data:
    :name: Container
    :type: object
    :content_type: container
    :permissions:
      :read_write: true
    :boost: 10000.0
    :features:
      :container:
        :excluded: ['Bild', 'Video']
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :headline:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :options:
            :data-validate: text
      :validity_period:
        :type: mixin
        :name: validity_period
      :description:
        :label: Beschreibung
        :type: string
        :storage_type: text
        :storage_location: column
        :search: true
        :editor:
          :type: quillEditor
          :options:
            :data-size: basic
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Container"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
