---
- :data:
    :name: Zitat
    :type: object
    :content_type: embedded
    :properties:
      :id:
        :label: id
        :type: key
      :text:
        :label: Fließtext
        :type: string
        :storage_location: translated_value
        :search: true
        :validations:
          :minLength: 1
        :ui:
          :edit:
            :type: quillEditor
            :options:
              :data-size: basic
      :image:
        :label: Bilder
        :type: linked
        :linked_table: creative_works
        :stored_filter: (name ?)
        :validations:
          :max: 1
        :ui:
          :edit:
            :type: objectBrowser
            :options:
              :data-validate: media
              :data-type: image
      :author:
        :label: "Zitat von"
        :type: linked
        :linked_table: persons
        :stored_filter: (name ?)
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: object
            :data-type: person
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Zitat"
      :meta_data:
        :type: mixin
        :name: meta_data
