- Inhaltstypen:
  - $$Asset:
    - $$Bild
    - $$Datei
    - $$Video
  - $$Person
  - $$Tour
  - $$POI
  - $$Unterkunft
  - $$Veranstaltung
  - $$Text:
    - $$Linktipps
    - $$Quiz
    - $$Angebot
    - $$Artikel
    - $$Biografie
    - $$Interview
    - $$Social Media Posting
    - $$Rezept
# hidden
  - $$Organisation
  - $$Zeitleiste
  - $$Örtlichkeit
# embedded
  - $$Angebotszeitraum
  - $$Website
  - $$Zeitleiste-Eintrag
  - $$Zitat
  - $$Frage
  - $$Antwort
  - $$Veranstaltungstermin
  - $$Öffnungszeit
  - $$Overlay
  - $$Publikations-Plan
  - $$Textblock
# container
  - $$Container

- Geschlecht:
  - Männlich
  - Weiblich

- Wochentage:
  - Montag
  - Dienstag
  - Mittwoch
  - Donnerstag
  - Freitag
  - Samstag
  - Sonntag

- Tags:

- Ausgabekanäle:

- Rezept-Gänge:

- Rezept-Kategorien:

- POI - Kategorien:
