---
name: Booking
credentials:
  host: https://distribution-xml.booking.com/2.1/json
  region_id: 1751 # Bodensee .... 1195 -> ganz Vorarlberg
  user: 'bodenseevo'
  password: 'Booking2016!'
default_options:
  locales: [de]
config:
  download_config:
    regions:
      sorting: 1
      source_type: regions
      endpoint: DataCycleCore::Generic::Booking::Endpoint
      download_strategy: DataCycleCore::Generic::Booking::DownloadRegions
    hotel_types:
      sorting: 2
      source_type: hotel_types
      endpoint: DataCycleCore::Generic::Booking::Endpoint
      download_strategy: DataCycleCore::Generic::Booking::DownloadHotelTypes
    hotels:
      sorting: 3
      source_type: hotels
      endpoint: DataCycleCore::Generic::Booking::Endpoint
      download_strategy: DataCycleCore::Generic::Booking::Download
  import_config:
    hotel_types:
      sorting: 1
      source_type: hotel_types
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: Booking.com - HotelTypes
      tag_id_path: 'hotel_type_id'
      tag_name_path: 'translations.name'
      external_id_prefix: 'Booking.com - HotelTypes - '
    hotel_facility_types:
      sorting: 2
      source_type: hotels
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: Booking.com - HotelFacilityTypes
      tag_id_path: 'hotel_data.hotel_facilities.hotel_facility_type_id'
      tag_name_path: 'hotel_data.hotel_facilities.name'
      external_id_prefix: 'Booking.com - HotelFacilityTypes - '
    image_keywords:
      sorting: 3
      source_type: hotels
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: Booking.com - Tags
      tag_id_path: 'hotel_data.hotel_photos.tags'
      tag_name_path: 'hotel_data.hotel_photos.tags'
      external_id_prefix: 'Booking.com - Tag - '
    hotels:
      sorting: 4
      source_type: hotels
      import_strategy: DataCycleCore::Generic::Booking::Import
      transformations:
        image:
          template: Bild
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Bild
        hotel:
          template: Unterkunft
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Unterkunft
