---
name: Celum
credentials:
  host: http://media.austrianwine.com/api/
  user: admin
  password: 'd9ZdhuxEdSPLJdk)av9RHyeh'
default_options:
  locales: [de]
config:
  download_config:
    keywords:
      sorting: 1
      source_type: keywords
      endpoint: DataCycleCore::Generic::Celum::Endpoint
      download_strategy: DataCycleCore::Generic::Celum::DownloadVerbose
    keyword_catalogs:
      sorting: 2
      source_type: keyword_catalogs
      endpoint: DataCycleCore::Generic::Celum::Endpoint
      download_strategy: DataCycleCore::Generic::Celum::DownloadVerbose
    users:
      sorting: 3
      source_type: users
      endpoint: DataCycleCore::Generic::Celum::Endpoint
      download_strategy: DataCycleCore::Generic::Celum::Download
    user_groups:
      sorting: 4
      source_type: user_groups
      endpoint: DataCycleCore::Generic::Celum::Endpoint
      download_strategy: DataCycleCore::Generic::Celum::Download
    folders:
      sorting: 5
      source_type: folders
      endpoint: DataCycleCore::Generic::Celum::Endpoint
      download_strategy: DataCycleCore::Generic::Celum::DownloadVerbose
    documents:
      sorting: 10
      source_type: documents
      endpoint: DataCycleCore::Generic::Celum::Endpoint
      download_strategy: DataCycleCore::Generic::Celum::DownloadVerbose
  import_config:
    keywords:
      sorting: 1
      source_type: keywords
      import_strategy: DataCycleCore::Generic::Celum::ImportKeywords
      tree_label: Celum - Keywords
      locales: [de]
    # keyword_catalogs:
    #   sorting: 2
    #   source_type: keyword_catalogs
    #   import_strategy: DataCycleCore::Generic::Celum::ImportKeywordCatalogs
    #   tree_label: Celum - KeywordCatalogs
    #   locales: [de]
    folders:
      sorting: 3
      source_type: folders
      import_strategy: DataCycleCore::Generic::Celum::ImportFolders
      tree_label: Celum - Folders
      locales: [de]
    persons:
      sorting: 8
      source_type: users
      import_strategy: DataCycleCore::Generic::Celum::ImportPersons
      locales: [de]
    images:
      sorting: 10
      source_type: documents
      source_filter:
        'dump.de.assetType.#cdata-section': '1'
        'dump.de.fileExtension.#cdata-section':
          $in:
            - 'png'
            - 'gif'
            - 'jpg'
            - 'jpeg'
      import_strategy: DataCycleCore::Generic::Celum::ImportDocuments
      locales: [de]
      transformations:
        images:
          asset_type: DataCycleCore::Image
