---
name: DataCycle - Media
credentials:
  storage_type: local
  directory: ./test/fixtures/files
#  directory: /home/pixelpoint/data_cycle_core/media
  delete: false
config:
  download_config:
    # could be used to download assets to local storage
    images:
      sorting: 1
      source_type: images
      endpoint:  DataCycleCore::Generic::DataCycleMedia::Endpoint
      download_strategy:  DataCycleCore::Generic::DataCycleMedia::Download
  import_config:
    images:
      sorting: 1
      source_type: images
      asset_type: DataCycleCore::Image
      import_strategy: DataCycleCore::Generic::DataCycleMedia::ImportAssets
      transformations:
        asset:
          template: Bild
    videos:
      sorting: 2
      source_type: videos
      asset_type: DataCycleCore::Video
      import_strategy: DataCycleCore::Generic::DataCycleMedia::ImportAssets
      transformations:
        asset:
          template: Video
    audio:
      sorting: 3
      source_type: audio
      asset_type: DataCycleCore::Audio
      import_strategy: DataCycleCore::Generic::DataCycleMedia::ImportAssets
      transformations:
        asset:
          template: Audio
    pdf:
      sorting: 4
      source_type: pdf
      asset_type: DataCycleCore::Pdf
      import_strategy: DataCycleCore::Generic::DataCycleMedia::ImportAssets
      transformations:
        asset:
          template: PDF
