---
name: Veranstaltungsdatenbank
credentials:
  action: /endpoints/58de77772158b76b42001b83
  end_point: /api/v2
  host: http://veranstaltungen.kaernten.at
config:
  download: DataCycleCore::Generic::BatchDownload
  download_config:
    categories:
      sorting: 1
      source_type: categories
      endpoint: DataCycleCore::Generic::EventDatabase::Endpoint
      download_strategy: DataCycleCore::Generic::EventDatabase::DownloadCategories
      logging_strategy: DataCycleCore::Generic::Logger::Console.new("download")
    events:
      sorting: 2
      source_type: events
      endpoint: DataCycleCore::Generic::EventDatabase::Endpoint
      download_strategy: DataCycleCore::Generic::EventDatabase::Download
      logging_strategy: DataCycleCore::Generic::Logger::Console.new("download")
  import: DataCycleCore::Generic::BatchImport
  import_config:
    categories:
      sorting: 1
      source_type: categories
      import_strategy: DataCycleCore::Generic::EventDatabase::ImportCategories
      data_template: ''
      tree_label: Veranstaltungsdatenbank - Kategorien
      target_type: DataCycleCore::Classification
      logging_strategy: DataCycleCore::Generic::Logger::Console.new("import")
    events:
      sorting: 2
      source_type: events
      import_strategy: DataCycleCore::Generic::EventDatabase::ImportEvents
      data_template: Event
      target_type: DataCycleCore::Event
      logging_strategy: DataCycleCore::Generic::Logger::Console.new("import")
