---
name: External System Test
credentials:
  key: khvc4nsccdhgcn347a7bxgne
  token: Bearer tgNpYjGbeehT7q4lnn1JAlXNVUbfEuJtuJVr6G7TxnYzY2Q4OWY1NjEwNDZhY2M3MmIxYjk1YmVkOTZlOTdmOQ==
  refresh_token: QKuKph4xVtKcY10stmXXw6lrsJSThA2oFLVHont8Wns2MWUwNmVlZWNkNjg2YWYyY2Y3NWMyYWUzZDRlOGExMw==
  base_url: https://api2.sprinklr.com/prod0/api/v1/sam
  import_url: https://api2.sprinklr.com/prod0/api/v1/sam/importUrl
config_out:
  push_config:
    sorting: 1
    create:
      webhook: Sprinklr::Webhooks::Create
      filter: Sprinklr::Webhooks::Create
    update:
      webhook: Sprinklr::Webhooks::Update
      filter: Sprinklr::Webhooks::Update
    delete:
      webhook: Sprinklr::Webhooks::Delete
      filter: Sprinklr::Webhooks::Delete
  refresh_config:
    webhook: RefreshTest
