---
name: 'OutdoorActive'
credentials:
  project: 'ar-kaernten'
  key: '71bf10dbf6f38ce14b94019c729e355'
  host: https://www.outdooractive.com
  end_point: api/project
default_options:
  locales: ['de']
config:
  download_config:
    categories:
      sorting: 1
      source_type: categories
      endpoint: DataCycleCore::Generic::OutdoorActive::Endpoint
      endpoint_method: tour_categories
      download_strategy: DataCycleCore::Generic::OutdoorActive::Download
    regions:
      sorting: 2
      source_type: regions
      endpoint: DataCycleCore::Generic::OutdoorActive::Endpoint
      download_strategy: DataCycleCore::Generic::OutdoorActive::Download
    places:
      sorting: 3
      source_type: places
      endpoint: DataCycleCore::Generic::OutdoorActive::Endpoint
      download_strategy: DataCycleCore::Generic::OutdoorActive::Download
    tours:
      sorting: 4
      source_type: tours
      endpoint: DataCycleCore::Generic::OutdoorActive::Endpoint
      download_strategy: DataCycleCore::Generic::OutdoorActive::Download
  import_config:
    categories:
      sorting: 1
      source_type: categories
      import_strategy: DataCycleCore::Generic::OutdoorActive::ImportCategories
      tree_label: OutdoorActive - Kategorien
    regions:
      sorting: 2
      source_type: regions
      import_strategy: DataCycleCore::Generic::OutdoorActive::ImportRegions
      tree_label: OutdoorActive - Regionen
    source_places:
      sorting: 3
      source_type: places
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: OutdoorActive - Quellen
      tag_id_path: 'meta.source.id'
      tag_name_path: 'meta.source.name'
      external_id_prefix: 'SOURCE:'
    source_tours:
      sorting: 4
      source_type: tours
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: OutdoorActive - Quellen
      tag_id_path: 'meta.source.id'
      tag_name_path: 'meta.source.name'
      external_id_prefix: 'SOURCE:'
    frontendtype_places:
      sorting: 5
      source_type: places
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: OutdoorActive - FrontendTypes
      tag_id_path: 'frontendtype'
      tag_name_path: 'frontendtype'
      external_id_prefix: 'FRONTENDTYPE:'
      external_id_hash_method: 'MD5'
    frontendtype_tours:
      sorting: 6
      source_type: tours
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: OutdoorActive - FrontendTypes
      tag_id_path: 'frontendtype'
      tag_name_path: 'frontendtype'
      external_id_prefix: 'FRONTENDTYPE:'
      external_id_hash_method: 'MD5'
    tag_places:
      sorting: 5
      source_type: places
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: OutdoorActive - Tags
      tag_id_path: 'properties.property.tag'
      tag_name_path: 'properties.property.text'
      external_id_prefix: 'TAG:'
    tag_tours:
      sorting: 6
      source_type: tours
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: OutdoorActive - Tags
      tag_id_path: 'properties.property.tag'
      tag_name_path: 'properties.property.text'
      external_id_prefix: 'TAG:'
    tours:
      sorting: 20
      source_type: tours
      import_strategy: DataCycleCore::Generic::OutdoorActive::ImportTours
      transformations:
        image:
          content_type: DataCycleCore::CreativeWork
          template: Bild
        tour:
          content_type: DataCycleCore::Thing
          template: Tour
    places:
      sorting: 21
      source_type: places
      import_strategy: DataCycleCore::Generic::OutdoorActive::ImportPlaces
      transformations:
        image:
          content_type: DataCycleCore::CreativeWork
          template: Bild
        place:
          content_type: DataCycleCore::Thing
          template: POI
