---
name: V-Ticket
credentials:
  action: /events
  end_point: /api/v2
  host: https://eventserver.v-ticket.at
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImU4NWFmMmE4ZDRmMTMxMjBmNWIyM2MxNzU1MzZkYjA1ODYxMTY2NjQ2M2YzNGM0NTk0ZDVkODFiOTBmMGU4MWFhNzVjY2E5YWQ1OTgzZmE0In0.eyJhdWQiOiIxIiwianRpIjoiZTg1YWYyYThkNGYxMzEyMGY1YjIzYzE3NTUzNmRiMDU4NjExNjY2NDYzZjM0YzQ1OTRkNWQ4MWI5MGYwZTgxYWE3NWNjYTlhZDU5ODNmYTQiLCJpYXQiOjE1NDQ3NzYxNDYsIm5iZiI6MTU0NDc3NjE0NiwiZXhwIjoxNTc2MzEyMTQ2LCJzdWIiOiIxMyIsInNjb3BlcyI6W119.UaclKjOOTPHED3eNDpNs7Lk5s-pWI16o11gXBORvO0ZIfvzJz1eBS9j1qFHGl_x2PwUR-4QEabbOihxIvUwNAkV2aGAAQUacDO5UHhyvNHGYWXhtYUCclUAlK9R0Ozmy22V6bQTC0umqQLGEcm1oBtD2HZtUKPTCFxn6CZeAVqv-x0Dcz3h65saehXlnnV9Ynz9T1PeorOXDiEc0R9j_diRsQ0vKl27fxfK-H3mhVERAfpH-iODe9zUqz5FUFZMn049OVsBErOkmL4mtc3XI0l2w2EcfK9QOQhL_kkd65CgBLbuQMmeHnp70khZ75qifLms0ZMhQpMDJuxTUnOM_6V49YgYQLeaqBjo9UoNMYkthDp1_gfFmuVv04ufA8xrB5WOx-lL4gnW9iqQc52sGw5hi8kSr2Oky_SH5OBfliwFeaV00Pgqiz--GcyBIV42uueluNErA0oH0KY2oeyNvMn5nxfuzDPf8pK4p97Uf2iXRxf6nmNS0burQeefRlO-kz5HVPEqEB1RjlwKSxt8ECvRA--t5KJQ-P2ST91jPnuVQWbK6jy0jfYSXdct72jD9UjTWsuFgKW49XmyBkQtdYwsZ1IccEni2UquxSMSp4WBynHkp9QvYQxBDbuRQQoaw8VCoCO8AqeqQRPnZ1ca01YZd_scUMsY1dazghqM5eaU'
default_options:
  locales: [de]
config:
  download_config:
    events:
      sorting: 2
      source_type: events
      endpoint: DataCycleCore::Generic::VTicket::Endpoint
      download_strategy: DataCycleCore::Generic::VTicket::Download
  import_config:
    tags:
      sorting: 1
      source_type: events
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: VTicket - Tags
      tag_id_path: 'tags'
      tag_name_path: 'tags'
      external_id_prefix: 'VTicket - Tags - '
    categories:
      sorting: 1
      source_type: events
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: VTicket - Categories
      tag_id_path: 'categories'
      tag_name_path: 'categories'
      external_id_prefix: 'VTicket - Categories - '
    events:
      sorting: 3
      source_type: events
      import_strategy: DataCycleCore::Generic::VTicket::ImportEvents
      transformations:
        image:
          template: Bild
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Bild
        place:
          template: Örtlichkeit
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Örtlichkeit
        event:
          template: Event
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Veranstaltung
          embedded:
            sub_event:
              template: SubEvent
              default_values:
                data_type:
                  tree_label: Inhaltstypen
                  value: Veranstaltungstermin
