---
- :data:
    :name: content_classifications
    :type: mixin
    :properties:
      :tags:
        :label: Tags
        :type: classification
        :tree_label: Tags
      :output_channel:
        :label: Ausgabekanal
        :type: classification
        :tree_label: Ausgabekanäle
