---
- :data:
    :name: geo
    :type: mixin
    :properties:
      :longitude:
        :label: Longitude
        :type: number
        :storage_location: column
        :validations:
          :format: float
        :api:
          :transformation:
            :method: nest
            :name: geo
            :type: GeoCoordinates
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true
      :latitude:
        :label: Latitude
        :type: number
        :storage_location: column
        :validations:
          :format: float
        :api:
          :transformation:
            :method: nest
            :name: geo
            :type: GeoCoordinates
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true
      :elevation:
        :label: Meereshöhe (m)
        :type: number
        :storage_location: column
        :validations:
          :format: float
        :api:
          :transformation:
            :method: nest
            :name: geo
            :type: GeoCoordinates
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true
      :location:
        :label: GPS-Koordinaten
        :type: geographic
        :storage_location: column
        :api:
          :disabled: true
