---
- :data:
    :name: postal_address
    :type: mixin
    :properties:
      :address:
        :label: Adresse
        :type: object
        :storage_location: value
        :api:
          :type: PostalAddress
        :properties:
          :street_address:
            :label: Straße
            :type: string
            :storage_location: value
            :normalize:
              :id: street
              :type: street
          :postal_code:
            :label: PLZ
            :type: string
            :storage_location: value
            :normalize:
              :id: zip
              :type: zip
          :address_locality:
            :label: Ort
            :type: string
            :storage_location: value
            :normalize:
              :id: city
              :type: city
          :address_country:
            :label: Land
            :type: string
            :storage_location: value
            :normalize:
              :id: country
              :type: country
