---
- :data:
    :name: additional_lodging_business_properties
    :type: mixin
    :properties:
      :additional_information:
        :label: Ergänzende Information
        :type: embedded
        :template_name: Ergänzende Information
        :api:
          :name: subject_of
      :number_of_rooms:
        :label: Anzahl Zimmer/Apartments/Stellplätze
        :type: number
        :storage_location: value
      :opening_hours_specification:
        :label: Öffnungszeit
        :type: embedded
        :template_name: Öffnungszeit
        :translated: true
      :contains_place:
        :label: Services
        :type: linked
        :template_name: Zimmer
        :translated: true
      :makes_offer:
        :label: Angebote
        :type: embedded
        :template_name: Angebot
        :translated: true
      # move to dataCycleProperty
      :price_range:
        :label: Preis-Info
        :type: string
        :storage_location: translated_value
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :aggregate_rating:
        :label: Durchschnittswertung
        :type: embedded
        :template_name: Durchschnittswertung
        :translated: true
