---
- :data:
    :name: place_attributes
    :type: mixin
    :properties:
      :description:
        :label: Kurzbeschreibung
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :text:
        :label: Beschreibung
        :type: string
        :storage_location: translated_value
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
      :primary_image:
        :label: Hauptbild
        :type: linked
        :template_name: Bild
        :validations:
          :max: 1
        :api:
          :name: image
          :minimal: true
      :image:
        :label: Bilder
        :type: linked
        :template_name: Bild
        :api:
          :name: photo
          :minimal: true
      :logo:
        :label: Logo
        :type: linked
        :template_name: Bild
        :api:
          :minimal: true
      :linked_thing:
        :label: Verknüpfte Inhalte
        :type: linked
        :inverse_of: is_linked_to
        :global: true
        :stored_filter:
          -
            :with_classification_aliases_and_treename:
              :treeLabel: Inhaltstypen
              :aliases:
                - Person
                - Organisation
                - Ort
                - Veranstaltung
                - Veranstaltungsserie
      :is_linked_to:
        :label: Verknüpft mit
        :type: linked
        :inverse_of: linked_thing
        :link_direction: inverse
        :global: true
      :subject_of:
        :label: Thema von
        :type: linked
        :inverse_of: about
        :link_direction: inverse
        :global: true
