image: patrickrainer/data_cycle_base:2.5.1

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: postgres
  POSTGRES_DB: data-cycle-base_test
  POSTGRES_PORT: "5432"
  MONGODB_HOST: mongodb
  RAILS_ENV: test
  TZ: Europe/Vienna

stages:
  - build
  - test
  - check
  - deploy

before_script:
# uncomment for local testing (via local gitlab-runner)
# delete me
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
# uncomment for local testing END
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan git.pixelpoint.biz >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  - bundle install --path=cache/bundler

  - dpkg-reconfigure -f noninteractive tzdata
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

  - cd $CI_PROJECT_DIR

cache:
  key: application-cache
  untracked: false
  paths:
    - cache/bundler
    - node_modules
    - lib/assets

services:
  - name: mdillon/postgis:9.6
    alias: postgres
  - name: mvertes/alpine-mongo:3.6.3-0
    alias: mongodb

# build caches
build_caches:
  stage: build
  tags:
    - data-cycle-core
  only:
    - master
    - release
    - pre-release
    - develop
  script:
    - bundle install --path=cache/bundler
    - yarn
    - npx gulp production

# Running tests
rails_test:
  tags:
    - data-cycle-core
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  only:
    - master
    - release
    - pre-release
    - develop
  script:
    - bundle exec rake db:drop
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake db:seed
    - bundle exec rails test -b

cypress:
  tags:
    - data-cycle-core
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  only:
    - master
    - release
    - pre-release
    - develop
  script:
    - bundle exec rake db:drop
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake db:seed
    - bundle exec rake app:data_cycle_core:update:import_classifications
    - bundle exec rake app:data_cycle_core:update:import_templates
    - cd test/dummy && bundle exec rails server -b 0.0.0.0 -p 3000 -d
    - cd $CI_PROJECT_DIR && npx cypress run
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_cypress"
    paths:
    - cypress/screenshots/
    expire_in: 1 week
    when: on_failure

# code validation
# bundle-audit
# brakeman
# rubocop
code_validation:
  tags:
    - data-cycle-core
  stage: check
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  only:
    - master
    - release
    - pre-release
    - develop
  script:
    - bundle exec bundle-audit update
    - bundle exec bundle audit check
    - bundle exec brakeman
    - bundle exec rubocop --format fuubar

# deployment
deploy_release:
  tags:
    - data-cycle-core
  stage: deploy
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  script:
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bundle exec cap release deploy
  only:
    - release
  environment:
    name: release
    url: http://core-production.datacycle.at/
  when: manual
  allow_failure: false

# deployment
deploy_pre_release:
  tags:
    - data-cycle-core
  stage: deploy
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  script:
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bundle exec cap pre_release deploy
  only:
    - pre-release
  environment:
    name: pre-release
    url: http://core-pre-release.datacycle.at/
  when: manual
  allow_failure: false

# deployment
deploy_development:
  tags:
    - data-cycle-core
  stage: deploy
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  script:
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bundle exec cap development deploy
  only:
    - develop
  environment:
    name: development
    url: http://core-development.datacycle.at/
  when: manual
  allow_failure: false

############### Review Apps
# Build caches
build_review_caches:
  only:
    - branches
  except:
    - master
    - release
    - pre-release
    - develop
  stage: build
  tags:
    - data-cycle-review
  script:
    - bundle install --path=cache/bundler
    - yarn
    - npx gulp production

# Running tests
rails_review_test:
  only:
    - branches
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  except:
    - master
    - release
    - pre-release
    - develop
  tags:
    - data-cycle-review
  script:
    - bundle exec rake db:drop
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake db:seed
    - bundle exec rails test

cypress_review:
  only:
    - branches
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  except:
    - master
    - release
    - pre-release
    - develop
  tags:
    - data-cycle-review
  script:
    - bundle exec rake db:drop
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake db:seed
    - bundle exec rake app:data_cycle_core:update:import_classifications
    - bundle exec rake app:data_cycle_core:update:import_templates
    - cd test/dummy && bundle exec rails server -b 0.0.0.0 -p 3000 -d
    - cd $CI_PROJECT_DIR && npx cypress run
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_cypress"
    paths:
    - cypress/screenshots/
    expire_in: 1 week
    when: on_failure

# code validation
# bundle-audit
# brakeman
# rubocop
code_review_validation:
  stage: check
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  only:
    - branches
  except:
    - master
    - release
    - pre-release
    - develop
  tags:
    - data-cycle-review
  script:
    - bundle exec bundle-audit update
    - bundle exec bundle audit check
    - bundle exec brakeman
    - bundle exec rubocop --format fuubar

deploy_review:
  stage: deploy
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - lib/assets
    policy: pull
  script:
    - bundle exec rake app:tmp:create
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bundle exec cap review deploy:initial branch=$CI_COMMIT_REF_NAME application=$CI_COMMIT_REF_SLUG
  only:
    - branches
  except:
    - master
    - release
    - pre-release
    - develop
    - remote-develop
  tags:
    - data-cycle-review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://core-$CI_COMMIT_REF_SLUG.datacycle.at
    on_stop: stop_review
  when: manual
  allow_failure: false

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    # uncomment for local testing
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    # uncomment for local testing END
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.pixelpoint.biz >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - git init
    - git remote add origin $CI_REPOSITORY_URL
    - git fetch
    - git reset origin/develop
    - git checkout -t origin/develop
    - git reset origin/develop --hard

    - bundle install --path=cache/bundler

    - cd $CI_PROJECT_DIR
  script:
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bundle exec cap review review:undeploy application=$CI_COMMIT_REF_SLUG
  only:
    - branches
  except:
    - master
    - release
    - pre-release
    - develop
    - remote-develop
  tags:
    - data-cycle-review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
