########################################################################
######################### DOCKER setup for DC core

# @todo: update to latest ruby image in gitlab utility (master)
include:
  - project: 'datacycle/utilities/datacycle-gitlab'
    ref: feature/ruby_3
    file: '.gitlab-ci-dc-common.yml'

stages:
  - test

########################################################################
######################### Branch Configuration
.master_ci_config: &master_ci
  only:
    - develop
    - master
    - feature/ruby_3
  tags:
    - dc-opensource

.local_test_vars: &local_test_vars
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "password"
    POSTGRES_HOST: postgres
    POSTGRES_DB: data-cycle-base_test
    POSTGRES_PORT: "5432"
    MONGODB_HOST: mongodb
    #    POSTGRES_VERSION: 13
    RAILS_ENV: test
    TZ: Europe/Vienna

.rails_test_config:
  <<: *local_test_vars
  extends: .job_cache_config
  stage: test
  artifacts:
    name: "$CI_JOB_NAME"
    expire_in: 1 week
    paths:
      - coverage/
  services:
    - name: "git.pixelpoint.biz:5050/datacycle/utilities/datacycle-docker/postgres:latest"
      alias: postgres
      command: ["postgres"]
    - name: mongo:4.4.8-focal
      alias: mongodb
  script:
    - gem install bundler
    - bundle --version
    - bundle config set --local path 'cache/bundler'
    - bundle install
    - bundle list
    - yarn
    - yarn upgrade
    - ls -la
    - ls -la cache/bundler
    - ls -la node_modules
    - bundle exec rake -T
    - bundle exec rake db:drop
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake db:seed
    - VITE_RUBY_VITE_BIN_PATH=node_modules/.bin/vite RUBYOPT=-W0 bundle exec rails test -b -f --pride

########################################################################
######################### Docker / Develop
rails_test:
  <<: *master_ci
  extends: .rails_test_config
  variables:
    # CORE_RAKE_PREFIX: 'app:'
    VITE_RUBY_VITE_BIN_PATH: 'node_modules/.bin/vite'
    RAILS_ENV: 'test'
