# author: rainer@pixelpoint.at
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  # - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2.2
  # TargetRailsVersion: 5.2.3
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "cache/**/*"
    - "bash/**/*"
    # - "test/dummy/db/migrate_6_1/**/*"
    # - "test/dummy/db/migrate_7_0/**/*"

#Rails:
#  Enabled: true

#######################################################
########## Bundler
Bundler/OrderedGems:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

#######################################################
########## Layout
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/RedundantInitialize:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

#######################################################
########## Lint

#Lint/SplatKeywordArguments:
#  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

#######################################################
########## Style

Style/SlicingWithRange:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashSyntax:
  Exclude:
    - "app/views/data_cycle_core/api/v2/api_base/**/*"

Style/MixinUsage:
  Exclude:
    - "bin/setup"
    - "bin/update"
    # - "test/dummy/bin/setup"
    # - "test/dummy/bin/update"

Style/MultilineBlockChain:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

# test
Style/HashTransformKeys:
  Enabled: false

# test
Style/HashTransformValues:
  Enabled: false

Style/RedundantStringEscape:
  Enabled: false

Style/OperatorMethodCall:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

#######################################################
########## Metrics
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

#######################################################
########## Naming

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

#######################################################
########## Rails

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/HelperInstanceVariable:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Rails/ApplicationController:
  Exclude:
    - "app/controllers/data_cycle_core/missing_asset_controller.rb"

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/DotSeparatedKeys:
  Enabled: false

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

Rails/TransactionExitStatement:
  Enabled: false

#######################################################
########## Rake
Rake/Desc:
  Enabled: false

Rake/MethodDefinitionInTask:
  Enabled: false

#######################################################
########## Minitest
# Minitest/AssertInDelta:
#   Enabled: false

# Minitest/AssertTruthy:
#   Enabled: false

# Minitest/AssertNil:
#   Enabled: false

# Minitest/RefuteFalse:
#   Enabled: false

# Minitest/RefuteEqual:
#   Enabled: false

# Minitest/AssertWithExpectedArgument:
#   Enabled: false

# Minitest/AssertPredicate:
#   Enabled: false

# Minitest/AssertEmptyLiteral:
#   Enabled: false

# Minitest/MultipleAssertions:
#   Enabled: false

# Minitest/AssertEqual:
#   Enabled: false

# Minitest/LiteralAsActualArgument:
#   Enabled: false

# Minitest/AssertIncludes:
#   Enabled: false

# Minitest/AssertionInLifecycleHook:
#   Enabled: false

# Minitest/AssertRespondTo:
#   Enabled: false

# Minitest/EmptyLineBeforeAssertionMethods:
#   Enabled: false

#######################################################
########## Security

Security/YAMLLoad:
  Exclude:
    - "app/models/data_cycle_core/master_data/import_classifications.rb"
    - "app/models/data_cycle_core/master_data/import_templates.rb"
    - "app/models/data_cycle_core/master_data/import_external_sources.rb"
    - "app/models/data_cycle_core/master_data/import_mixins.rb"
