version: '3.9'

services:
  postgres:
    image: 'git.pixelpoint.biz:5050/data-cycle/data-cycle-core/postgres:13.4'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_VERSION=${POSTGRES_VERSION:-13}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - RAILS_ENV=${RAILS_ENV:-development}
      - CORE_DUMMY_PREFIX=${CORE_DUMMY_PREFIX:-}
      - CORE_RAKE_PREFIX=${CORE_RAKE_PREFIX:-}
    entrypoint: ${DC_DOCKER_SETUP_PATH:-/app/docker/}postgres/entrypoint.sh
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - '127.0.0.1:${PUBLIC_POSTGRES_PORT:-5432}:5432'
    shm_size: 4gb
  mongodb:
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:${PUBLIC_MONGODB_PORT:-27017}:27017'
    entrypoint: ${DC_DOCKER_SETUP_PATH:-/app/docker/}mongodb/entrypoint.sh
    command: mongod --config /etc/mongo/mongod.conf
    environment:
      - MONGODB_CACHE_SIZE_GB=${MONGODB_CACHE_SIZE_GB:-1}
      - RAILS_ENV=${RAILS_ENV:-development}
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    entrypoint: ${DC_DOCKER_SETUP_PATH:-/app/docker/}redis/entrypoint.sh
    command: redis-server /etc/redis/redis.conf
    environment:
      - REDIS_MAX_MEMORY=${REDIS_MAX_MEMORY:-2gb}
      - RAILS_ENV=${RAILS_ENV:-development}
  nginx:
    image: nginx:1.21-alpine
    ports:
      - '${PUBLIC_NGINX_HOST-127.0.0.1:}${PUBLIC_APPLICATION_PORT:-3003}:${PUBLIC_APPLICATION_PORT:-3003}'
    entrypoint: ${DC_DOCKER_SETUP_PATH:-/app/docker/}nginx/entrypoint.sh
    command: ['nginx', '-g', 'daemon off;']
    environment:
      - APPLICATION_ROOT=${APPLICATION_ROOT:-/app}
      - PUBLIC_APPLICATION_PORT=${PUBLIC_APPLICATION_PORT:-3003}
      - PUBLIC_APPLICATION_HOST=${PUBLIC_APPLICATION_HOST:-localhost}
      - APP_PROTOCOL=${APP_PROTOCOL:-http}
      - IMGPROXY_PORT=${IMGPROXY_PORT:-9000}
      - IMGPROXY_DC_SIGNATURE_URL=${IMGPROXY_DC_SIGNATURE_URL:-http://nginx:3003}
      - RAILS_ENV=${RAILS_ENV:-development}
    depends_on:
      - web
      - imgproxy
  imgproxy:
    image: darthsim/imgproxy:v2.16
    environment:
      PORT: '${IMGPROXY_PORT:-9000}'
  varnish:
    build:
      context: ./docker/varnish
      dockerfile: Dockerfile
    entrypoint: ${DC_DOCKER_SETUP_PATH:-/app/docker/}varnish/entrypoint.sh
    command: "-s static=file,/var/lib/varnish/data/cache,${VARNISH_STATIC_SIZE:-10M} -f /var/lib/varnish/default.vcl"
    depends_on:
      - imgproxy
      - nginx
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
