version: '3.8'

x-app-env: &default-app-env
  APP_PROTOCOL: ${APP_PROTOCOL:-http}
  APP_HOST: ${APP_HOST:-localhost:3003}
  APPLICATION_ROOT: ${APPLICATION_ROOT:-/var/www/app}
  MONGODB_HOST: ${MONGODB_HOST:-mongodb}
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_VERSION: ${POSTGRES_VERSION:-13}
  PUBLIC_APPLICATION_PORT: ${PUBLIC_APPLICATION_PORT:-3003}
  RAILS_ENV: ${RAILS_ENV:-production}
  RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT:-false}
  REDIS_SERVER: ${REDIS_SERVER:-redis}
  SSH_AUTH_SOCK: /ssh-agent
  HISTFILE: /home/ruby/hist/.bash_history

x-app: &default-app
  build:
    context: ${PWD}
    target: production
    dockerfile: ${COMPOSE_WEB_DOCKER_FILE:-./vendor/gems/data-cycle-core/Dockerfile}
    args:
      - "RAILS_ENV=${RAILS_ENV:-production}"
      - "NODE_ENV=${NODE_ENV:-production}"
      - "APP_DOCKER_ENV=${APP_DOCKER_ENV:-production}"
  env_file:
    - ${PWD}/.env.deploy
  volumes:
    - app-tmp:/app/tmp
    - app-docker:/app/docker
    - app-assets:/app/public/assets
    - ${BASE_LOG_VOLUME_PATH:--./../../../log}/app:/app/log
    - ${BASE_DATA_VOLUME_PATH:-./../../../dcdata}/app:/app/public/uploads
    - ${BASE_HISTORY_VOLUME_PATH:-./../../../history}:/home/ruby/hist
    - ${BASE_BACKUP_VOLUME_PATH:-./../../../backups}:/app/db/backups
#    - ./docker/postgres/wait-for-postgres.sh:/app/docker/postgres/wait-for-postgres.sh
    - $SSH_AUTH_SOCK:/ssh-agent
  extra_hosts:
    - 'dockerhost:host-gateway'
#  stdin_open: true
#  tty: true
#  restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'

services:
  web:
    <<: *default-app
    environment:
      <<: *default-app-env
    entrypoint: /app/vendor/gems/data-cycle-core/docker/web/docker-entrypoint-production.sh
    command: ["/app/docker/postgres/wait-for-postgres.sh", "postgres", "/app/docker/setup.production.sh"]
  migrate_project:
    <<: *default-app
    environment:
      <<: *default-app-env
    command: ["/bin/bash"]
  job_worker_default:
    <<: *default-app
    environment:
      <<: *default-app-env
      QUEUE: default,mailers
    command: ["/app/docker/postgres/wait-for-postgres.sh", "postgres", "bundle", "exec", "bin/rake", "jobs:work"]
    depends_on:
      - web
  job_worker_importers:
    <<: *default-app
    environment:
      <<: *default-app-env
      QUEUE: importers
    command: ["/app/docker/postgres/wait-for-postgres.sh", "postgres", "bundle", "exec", "bin/rake", "jobs:work"]
    depends_on:
      - web
  job_worker_cache_invalidation:
    <<: *default-app
    environment:
      <<: *default-app-env
      QUEUE: cache_invalidation
    command: ["/app/docker/postgres/wait-for-postgres.sh", "postgres", "bundle", "exec", "bin/rake", "jobs:work"]
    depends_on:
      - web
  job_worker_search_update:
    <<: *default-app
    environment:
      <<: *default-app-env
      QUEUE: search_update
    command: ["/app/docker/postgres/wait-for-postgres.sh", "postgres", "bundle", "exec", "bin/rake", "jobs:work"]
    depends_on:
      - web
  job_worker_carrierwave:
    <<: *default-app
    environment:
      <<: *default-app-env
      QUEUE: carrierwave
    command: ["/app/docker/postgres/wait-for-postgres.sh", "postgres", "bundle", "exec", "bin/rake", "jobs:work"]
    depends_on:
      - web
  job_worker_webhooks:
    <<: *default-app
    environment:
      <<: *default-app-env
      QUEUE: webhooks
    command: ["/app/docker/postgres/wait-for-postgres.sh", "postgres", "bundle", "exec", "bin/rake", "jobs:work"]
    depends_on:
      - web
##    command: ["bundle", "exec", "bin/delayed_job", "-n 1", "--pool=importers:1", "--pool=cache_invalidation:2", "--pool=search_update:3", "--pool=carrierwave:1", "--pool=mailers:1", "--pool=webhooks:1", "--pool=default:1", "run"]
  scheduler:
    <<: *default-app
    environment:
      <<: *default-app-env
    command: bin/scheduler
    depends_on:
      - web
  postgres:
    image: 'git.pixelpoint.biz:5050/data-cycle/data-cycle-core/postgres:13.4'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_VERSION=${POSTGRES_VERSION:-13}
      - POSTGRES_EFFECTIVE_CACHE_SIZE=${POSTGRES_EFFECTIVE_CACHE_SIZE:-6GB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    entrypoint: /app/docker/postgres/setup.sh
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - ${PUBLIC_POSTGRES_PORT:-5432}:5432
    shm_size: 8gb
    volumes:
      - app-docker:/app/docker
      - ${BASE_DATA_VOLUME_PATH:-./../../../dcdata}/postgres:/var/lib/postgresql/data
#      - ./docker/postgres/postgresql.conf:/tmp/postgres/postgresql.conf
#      - ./docker/postgres/setup.sh:/tmp/postgres/setup-postgres.sh
#      - ${PWD}/config/configurations/ts_search:/tmp/postgres/ts_search
    depends_on:
      - web
  mongodb:
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    ports:
      - '${PUBLIC_MONGODB_PORT:-27017}:27017'
    entrypoint: /app/docker/mongodb/setup.sh
    command: mongod --config /etc/mongo/mongod.conf
    environment:
      - MONGODB_CACHE_SIZE_GB=${MONGODB_CACHE_SIZE_GB:-1}
    volumes:
      - app-docker:/app/docker
      - ${BASE_DATA_VOLUME_PATH:-./../../../dcdata}/mongodb:/data/db
      - ${BASE_LOG_VOLUME_PATH:--./../../../log}/mongodb:/var/log/mongodb
#      - ./docker/mongodb/mongod.conf:/tmp/mongodb/mongod.conf
#      - ./docker/mongodb/setup.sh:/tmp/mongodb/setup-mongodb.sh
    depends_on:
      - web
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    entrypoint: /app/docker/redis/setup.sh
    command: redis-server /etc/redis/redis.conf
    environment:
      - REDIS_MAX_MEMORY=${REDIS_MAX_MEMORY:-2gb}
    volumes:
      - app-docker:/app/docker
      - redis:/data
#      - ./docker/redis/redis.conf:/tmp/redis/redis.conf
#      - ./docker/redis/setup.sh:/tmp/redis/setup-redis.sh
    depends_on:
      - web
  nginx:
    image: nginx:1.21-alpine
    ports:
      - '${PUBLIC_APPLICATION_PORT:-3003}:${PUBLIC_APPLICATION_PORT:-3003}'
    entrypoint: /app/docker/nginx/setup.sh
    command: ["nginx", "-g", "daemon off;"]
    environment:
      # check if APPLICATION_ROOT can be removed (used in core)
      - APPLICATION_ROOT=${APPLICATION_ROOT:-/app}
      - PUBLIC_APPLICATION_PORT=${PUBLIC_APPLICATION_PORT:-3003}
      - PUBLIC_APPLICATION_HOST=${PUBLIC_APPLICATION_HOST:-localhost}
      - IMGPROXY_PORT=${IMGPROXY_PORT:-9000}
    volumes:
      - app-docker:/app/docker
      - app-tmp:/app/tmp
      - app-assets:/app/public/assets
      - ${BASE_LOG_VOLUME_PATH:--./../../../log}/nginx:/var/log/datacycle
      - ${BASE_CACHE_VOLUME_PATH:--./../../../cache}/imgproxy_data_cycle:/var/cache/nginx/imgproxy_data_cycle
      - ${BASE_CACHE_VOLUME_PATH:--./../../../cache}/data_cycle:/var/cache/nginx/data_cycle
#      - ${PWD}:/app
#      - './docker/nginx/templates/datacycle.conf.template:/etc/nginx/templates/datacycle.conf.template'
    depends_on:
      - web
      - imgproxy
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
  imgproxy:
    image: darthsim/imgproxy:v2.16
    env_file:
      - ${PWD}/.env.deploy
    environment:
      PORT: '${IMGPROXY_PORT:-9000}'
volumes:
  app-docker:
  app-tmp:
  app-assets:
#  gems:
  redis:
#  node-modules:
#  nginx:
#  app:
