# syntax=docker/dockerfile:1.2

FROM git.pixelpoint.biz:5050/data-cycle/data-cycle-core/base:latest

RUN echo "shopt -s histappend" >> /root/.bashrc
RUN echo "PROMPT_COMMAND=\"\${PROMPT_COMMAND}\${PROMPT_COMMAND:+;}history -a; history -n\"" >> /root/.bashrc

RUN mkdir -p /var/www/app

ENV GEM_HOME /gems
ENV BUNDLE_PATH $GEM_HOME
ENV BUNDLE_APP_CONFIG $BUNDLE_PATH
ENV BUNDLE_BIN $BUNDLE_PATH/bin

ENV PATH /app/bin:$BUNDLE_BIN:$PATH
ENV DUMMY_PATH /var/www/app/test/dummy

ADD Gemfile /var/www/app/Gemfile
ADD Gemfile.lock /var/www/app/Gemfile.lock

ADD data_cycle_core.gemspec /var/www/app/data_cycle_core.gemspec

ADD . /var/www/app
RUN chown -R nobody:nogroup /var/www/app
USER nobody

WORKDIR /var/www/app
