version: '3.8'
services:
  postgres:
    image: 'git.pixelpoint.biz:5050/data-cycle/data-cycle-core/postgres:13.4'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_EFFECTIVE_CACHE_SIZE=${POSTGRES_EFFECTIVE_CACHE_SIZE:-6GB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    entrypoint: /tmp/postgres/setup-postgres.sh
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - ${PUBLIC_POSTGRES_PORT:-5432}:5432
    shm_size: 8gb
    volumes:
      - ${BASE_DATA_VOLUME_PATH:-./../../../dcdata}/postgres:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/tmp/postgres/postgresql.conf
      - ./docker/postgres/setup.sh:/tmp/postgres/setup-postgres.sh
      - ${PWD}/config/configurations/ts_search:/tmp/postgres/ts_search
  mongodb:
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    ports:
      - '${PUBLIC_MONGODB_PORT:-27017}:27017'
    entrypoint: /tmp/mongodb/setup-mongodb.sh
    command: mongod --config /etc/mongo/mongod.conf
    environment:
      - MONGODB_CACHE_SIZE_GB=${MONGODB_CACHE_SIZE_GB:-1}
    volumes:
      - ${BASE_DATA_VOLUME_PATH:-./../../../dcdata}/mongodb:/data/db
      - ${BASE_LOG_VOLUME_PATH:--./../../../log}/mongodb:/var/log/mongodb
      - ./docker/mongodb/mongod.conf:/tmp/mongodb/mongod.conf
      - ./docker/mongodb/setup.sh:/tmp/mongodb/setup-mongodb.sh
  web:
    build:
      context: ${PWD}
      dockerfile: ${COMPOSE_WEB_DOCKER_FILE:-./vendor/gems/data-cycle-core/Dockerfile}
    env_file:
      - ${PWD}/.env.deploy
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - MONGODB_HOST=mongodb
      # validate
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_VERSION=${POSTGRES_VERSION:-13}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - ALLOW_IP_RANGE=172.18.0.0/12
      - TZ=Europe/Vienna
      - APPLICATION_ROOT=${APPLICATION_ROOT:-/var/www/app}
      - APP_PROTOCOL=${APP_PROTOCOL:-http}
      # @todo check app_host for local dev
      - APP_HOST=${APP_HOST:-localhost:3003}
      - PUBLIC_APPLICATION_PORT=${PUBLIC_APPLICATION_PORT:-3003}
      - SSH_AUTH_SOCK=/ssh-agent
      - HISTFILE=/root/hist/.bash_history
      # @todo obsolete VITE_RUBY_* settings ?
      - VITE_RUBY_HOST=0.0.0.0
      - VITE_RUBY_PORT=${PUBLIC_VITE_PORT:-3036}
    ports:
      # @todo remove obsolete port for production: run vite rake task
      - '${PUBLIC_VITE_PORT:-3036}:${PUBLIC_VITE_PORT:-3036}'
#    command: bundle exec puma -C /app/vendor/gems/data-cycle-core/docker/web/puma.rb
#      - ${COMPOSE_WEB_COMMAND:-./vendor/gems/data-cycle-core/docker/setup.production.sh}
    volumes:
#      - gems:/usr/local/bundle
#      - ${PWD}:/var/www/app
      - $SSH_AUTH_SOCK:/ssh-agent
#      - ${PWD}/docker/hist:/root/hist
#      - node-modules:/node_modules
#      - app-tmp:/app/tmp
      - app:/app
      - ${BASE_LOG_VOLUME_PATH:--./../../../log}/app:/app/log
#    user: root
    depends_on:
      - postgres
      - mongodb
      - redis
    stdin_open: true
    tty: true
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    entrypoint: /tmp/redis/setup-redis.sh
#    ports:
#      - '${PUBLIC_REDIS_PORT:-6379}:6379'
    command: redis-server /etc/redis/redis.conf
    environment:
      - REDIS_MAX_MEMORY=${REDIS_MAX_MEMORY:-2gb}
    volumes:
      - redis:/data
      - ./docker/redis/redis.conf:/tmp/redis/redis.conf
      - ./docker/redis/setup.sh:/tmp/redis/setup-redis.sh
  nginx:
    image: nginx:1.20-alpine
    ports:
      - '${PUBLIC_APPLICATION_PORT:-3003}:${PUBLIC_APPLICATION_PORT:-3003}'
    environment:
      # check if APPLICATION_ROOT can be removed (used in core)
      - APPLICATION_ROOT=${APPLICATION_ROOT:-/var/www/app}
      - PUBLIC_APPLICATION_PORT=${PUBLIC_APPLICATION_PORT:-3003}
      - PUBLIC_APPLICATION_HOST=${PUBLIC_APPLICATION_HOST:-localhost}
      - IMGPROXY_PORT=${IMGPROXY_PORT:-9000}
    volumes:
      - app:/app
      - ${BASE_LOG_VOLUME_PATH:--./../../../log}/app:/app/log
      - ${BASE_CACHE_VOLUME_PATH:--./../../../cache}/imgproxy_data_cycle:/var/cache/nginx/imgproxy_data_cycle
      - ${BASE_CACHE_VOLUME_PATH:--./../../../cache}/data_cycle:/var/cache/nginx/data_cycle
#      - ${BASE_LOG_VOLUME_PATH:--./../../../log}/nginx:/app/log
#      - ${PWD}:/var/www/app
      - './docker/nginx/templates/datacycle.conf.template:/etc/nginx/templates/datacycle.conf.template'
    depends_on:
      - web
      - imgproxy
    restart: unless-stopped
  imgproxy:
    image: darthsim/imgproxy:v2.16
    env_file:
      - ${PWD}/.env.deploy
    environment:
      PORT: '${IMGPROXY_PORT:-9000}'
volumes:
#  gems:
  redis:
#  node-modules:
#  nginx:
#  app-tmp:
  app:
