version: '2'
services:
  postgres:
    image: 'mdillon/postgis:9.6'
    environment:
    - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
    - '5446:5432'
  mongodb:
    image: 'mvertes/alpine-mongo:3.4.10-0'
    ports:
    - '27026:27017'
  web:
    build: .
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - POSTGRES_HOST=postgres
    - MONGODB_HOST=mongodb
    - ALLOW_IP_RANGE=172.18.0.0/12
    - TZ=Europe/Vienna
    command:
    - ./docker/setup.sh
    volumes:
    - 'gems:/gems'
    - '.:/var/www/app'
    user: root
    ports:
    - '3010:3000'
    links:
    - postgres
    - mongodb
    stdin_open: true
    tty: true
volumes:
  gems: