version: '3.9'

x-app-env: &default-app-env
  RAILS_ENV: ${RAILS_ENV:-development}
  MAILHOG_HOST: mailhog

x-app: &default-app
  build:
    context: ${PWD}
    target: development
    dockerfile: ${COMPOSE_WEB_DOCKER_FILE:-./vendor/gems/data-cycle-core/Dockerfile}
    args:
      - "RAILS_ENV=${RAILS_ENV:-development}"
      - "NODE_ENV=${NODE_ENV:-development}"
      - "APP_DOCKER_ENV=${APP_DOCKER_ENV:-development}"
  env_file:
    - ${PWD}/.env
  volumes:
    - '${PWD}:/app'
    - '${PWD}/docker/hist:/home/ruby/hist'
    - app-node-modules:/app/node_modules
    - $SSH_AUTH_SOCK:/ssh-agent
  stdin_open: true
  tty: true

services:
  web:
    <<: *default-app
    environment:
      <<: *default-app-env
#    entrypoint: /app/vendor/gems/data-cycle-core/docker/web/entrypoint-development.sh
    command: ["/app/vendor/gems/data-cycle-core/docker/postgres/wait-for-postgres.sh", "postgres", "/app/vendor/gems/data-cycle-core/docker/web/setup.development.sh"]
  postgres:
    entrypoint: /app/vendor/gems/data-cycle-core/docker/postgres/entrypoint.sh
    volumes:
      - '${PWD}:/app'
      - postgres-data:/var/lib/postgresql/data
  mongodb:
    entrypoint: /app/vendor/gems/data-cycle-core/docker/mongodb/entrypoint.sh
    volumes:
      - '${PWD}:/app'
      - mongodb-data:/data/db
      - mongodb-data:/var/log/mongodb
  redis:
    entrypoint: /app/vendor/gems/data-cycle-core/docker/redis/entrypoint.sh
    volumes:
      - '${PWD}:/app'
      - redis:/data
  nginx:
    entrypoint: /app/vendor/gems/data-cycle-core/docker/nginx/entrypoint.sh
    volumes:
      - '${PWD}:/app'
      - nginx-log:/var/log/datacycle
  imgproxy:
    env_file:
      - ${PWD}/.env
  mailhog:
    image: yappabe/mailhog
    environment:
      DNSDOCK_ALIAS: localhost
    ports:
      - '${PUBLIC_MAILHOG_PORT:-1025}:8025'
volumes:
  app-node-modules:
  mongodb-data:
  mongodb-log:
  nginx-log:
  postgres-data:
  redis:
