version: '3.8'
services:
  postgres:
    image: 'git.pixelpoint.biz:5050/data-cycle/data-cycle-core/postgres:13.1'
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: /tmp/postgres/setup-postgres.sh
    ports:
      - ${PUBLIC_POSTGRES_PORT:-5432}:5432
    shm_size: 8gb
    volumes:
      - ./docker/postgres/postgresql.conf:/etc/postgresql.conf
      - ./docker/setup-postgres.sh:/tmp/postgres/setup-postgres.sh
      - ${PWD}/config/configurations/ts_search:/tmp/postgres/ts_search
  mongodb:
    # db version v4.2.15
    # @todo add mongodb conf
    image: mongo:4.4.8-focal
    ports:
      - '${PUBLIC_MONGODB_PORT:-27017}:27017'
  web:
    build:
      context: ${PWD}
      dockerfile: ${COMPOSE_WEB_DOCKER_FILE:-./vendor/gems/data-cycle-core/Dockerfile}
    env_file:
      - ${PWD}/.env.deploy
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_VERSION=${POSTGRES_VERSION}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - MONGODB_HOST=mongodb
      - ALLOW_IP_RANGE=172.18.0.0/12
      - TZ=Europe/Vienna
      - APPLICATION_ROOT=${APPLICATION_ROOT:-/var/www/app}
      - APP_PROTOCOL=${APP_PROTOCOL:-http}
      # @todo check app_host for local dev
      - APP_HOST=${APP_HOST:-localhost:3003}
      - PUBLIC_APPLICATION_PORT=${PUBLIC_APPLICATION_PORT:-3003}
      - SSH_AUTH_SOCK=/ssh-agent
      - HISTFILE=/root/hist/.bash_history
      # @todo obsolete VITE_RUBY_* settings ?
      - VITE_RUBY_HOST=0.0.0.0
      - VITE_RUBY_PORT=${PUBLIC_VITE_PORT:-3036}
    ports:
      # @todo remove obsolete port for production: run vite rake task
      - '${PUBLIC_VITE_PORT:-3036}:${PUBLIC_VITE_PORT:-3036}'
    command:
      # @todo add setup.production.sh + rake vite:build
      - ${COMPOSE_WEB_COMMAND:-./vendor/gems/data-cycle-core/docker/setup.sh}
    volumes:
      - gems:/gems
      - ${PWD}:/var/www/app
      - $SSH_AUTH_SOCK:/ssh-agent
      - ${PWD}/docker/hist:/root/hist
      - node-modules:/var/www/app/node_modules
    user: root
    depends_on:
      - postgres
      - mongodb
      - redis
    stdin_open: true
    tty: true
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    command:
      - /tmp/redis/setup-redis.sh
    environment:
      - REDIS_MAX_MEMORY=${REDIS_MAX_MEMORY:-2gb}
    volumes:
      - 'redis:/data'
      - './docker/redis/redis.conf:/tmp/redis/redis.conf'
      - ./docker/setup-redis.sh:/tmp/redis/setup-redis.sh
  nginx:
    image: nginx:1.20-alpine
    ports:
      - '${PUBLIC_APPLICATION_PORT:-3003}:${PUBLIC_APPLICATION_PORT:-3003}'
    environment:
      # check if APPLICATION_ROOT can be removed (used in core)
      - APPLICATION_ROOT=${APPLICATION_ROOT:-/var/www/app}
      - PUBLIC_APPLICATION_PORT=${PUBLIC_APPLICATION_PORT:-3003}
      - PUBLIC_APPLICATION_HOST=${PUBLIC_APPLICATION_HOST:-localhost}
      - IMGPROXY_PORT=${IMGPROXY_PORT:-9000}
    volumes:
      - ${PWD}:/var/www/app
      - './docker/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template'
    depends_on:
      - web
      - imgproxy
    restart: unless-stopped
  imgproxy:
    image: darthsim/imgproxy:v2.16
    env_file:
      - ${PWD}/.env.deploy
    environment:
      PORT: '${IMGPROXY_PORT:-9000}'
volumes:
  gems:
  redis:
  nginx:
  node-modules:
