version: '3.8'
services:
  web:
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock # SSH-forwarding for Mac
    command:
      - ./docker/setup_mac.sh # For now, we are not using puma sockets because the sync does not work correctly
    volumes:
    - core-web-sync:/var/www/app:nocopy # use different names for different projects
    - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock  # SSH-forwarding for Mac
  nginx:
    volumes:
      - './docker/nginx/default_mac.conf:/etc/nginx/conf.d/default.conf' # For now, we are not using puma sockets because the sync does not work correctly

volumes:
  core-web-sync: # use different names for different projects
    external: true
