version: '2'
services:
  postgres:
    image: 'mdillon/postgis:9.6'
    environment:
    - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
    - '5446:5432'
  mongodb:
    image: 'mvertes/alpine-mongo:3.4.10-0'
    ports:
    - '27026:27017'
  web:
    build: .
    environment:
#    - RAILS_ENV=test
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - MONGODB_HOST=mongodb
    - ALLOW_IP_RANGE=172.18.0.0/12
    - TZ=Europe/Vienna
    - APP_HOST=localhost:3010
    - APP_PROTOCOL=http
    - MAILHOG_HOST=mailhog
    command:
    - ./docker/setup.sh
    volumes:
    - 'gems:/gems'
    - '.:/var/www/app'
    user: root
    ports:
    - '3010:3000'
    links:
    - postgres
    - mongodb
    stdin_open: true
    tty: true
  mailhog:
    image: yappabe/mailhog
    environment:
      DNSDOCK_ALIAS: localhost
    ports:
      - '1035:8025'
  redis:
    image: 'redis:latest'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
    - '6380:6379'
  redis-commander:
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081
volumes:
  gems:
  redis:
