version: '3.8'
services:
  web:
    volumes:
      - $COMPOSE_PROJECT_NAME-sync:/var/www/app:nocopy # use different names for different projects
  nginx:
    volumes:
      - './docker/nginx/templates/default_mac.conf.template:/etc/nginx/templates/default.conf.template' # For now, we are not using puma sockets because the sync does not work correctly

volumes:
  '$COMPOSE_PROJECT_NAME-sync': # use different names for different projects
    external: true
