- Inhaltstypen:
  - $$Text:
    - $$Artikel
    - $$Angebot
    - $$Biografie
    - $$Interview
    - $$Social Media Posting
  - $$Asset:
    - $$Bild
    - $$Datei
    - $$Video
  - $$Linktipps
  - $$Person
  - $$Organisation
  - $$Ort:
    - $$Örtlichkeit
  - $$Quiz
  - $$Veranstaltung
  - $$Zeitleiste
  - $$Rezept
# embedded
  - $$Angebotszeitraum
  - $$Website
  - $$Zeitleiste-Eintrag
  - $$Zitat
  - $$Frage
  - $$Antwort
  - $$Veranstaltungstermin

- Geschlecht:
  - Männlich
  - Weiblich

- Ausgabekanäle:
  - Web
  - Social Media
  - Print

- Themenbereiche:

- Tags:
