- Inhaltstypen:
  - $$Text:
    - $$Artikel
    - $$Angebot
    - $$Biografie
    - $$Interview
    - $$Social Media Posting
    - $$Zitat
  - $$Assets:
    - $$Bild
    - $$Datei
  - $$Linktipps
  - $$Person
  - $$Organisation
  - $$Ort:
    - $$Örtlichkeit
  - $$Quiz
  - $$Veranstaltung
  - $$Zeitleiste
# embedded
  - $$Angebotszeitraum
  - $$Website
  - $$Zeitleiste-Eintrag
  - $$Zitat
  - $$Frage
  - $$Antwort
  - $$Veranstaltungstermin

- Geschlecht:
  - Männlich
  - Weiblich

- Themenbereiche:

- Ausgabekanäle:
