data_link_create:
  actions: create_editable_links
  segment: SubjectByConditions
  parameters: DataCycleCore::DataLink

data_link_actions:
  actions: [read, create, update, destroy]
  segment: SubjectByUserAndConditions
  parameters:
    - DataCycleCore::DataLink
    - :creator_id

object_browser:
  actions: [show, find]
  segment: SubjectByConditions
  parameters: :object_browser

user_api_login:
  actions: [login, renew_login, reset_password, confirm]
  segment: SubjectByConditions
  parameters: :user_api

asset_read:
  actions: read
  segment: AssetByUserAndNoContent

asset_create_duplicate:
  actions: create_duplicate
  segment: SubjectByConditions
  parameters: DataCycleCore::Asset

asset_create:
  actions: [create, update, destroy]
  segment: SubjectByUserAndConditions
  parameters:
    - DataCycleCore::Asset
    - :creator_id

thing_create:
  actions: create
  segment: TemplateByCreatableScope
  parameters: :all

thing_print:
  actions: print
  segment: ThingByContentType
  parameters: entity

thing_actions:
  actions:
    - show_related
    - show_external_connections
    - subscribe
    - history
    - view_life_cycle
  segment: SubjectByConditions
  parameters: DataCycleCore::Thing

thing_history:
  actions: history
  segment: SubjectByConditions
  parameters: DataCycleCore::Thing::History

thing_edit:
  actions: [read, update, import, set_life_cycle, move_content]
  segment: ContentIsEditable
  parameters:
    - - :content_not_external?
      - :content_overlay_allowed?
      - :content_global_property_names_present?

thing_destroy:
  actions: destroy
  segment: SubjectByUserAndConditions
  parameters:
    - DataCycleCore::Thing
    - :created_by

stored_filter_actions:
  actions: [read, create, update, destroy, show_history, change_owner]
  segment: SubjectByUserAndConditions
  parameters:
    - DataCycleCore::StoredFilter
    - :user_id

watch_list_subscribe:
  actions: subscribe
  segment: SubjectByConditions
  parameters: DataCycleCore::WatchList

watch_list_actions:
  actions: [read, create, update, add_item, remove_item]
  segment: SubjectByUserAndConditions
  parameters:
    - DataCycleCore::WatchList
    - :user_id

watch_list_actions_except_my_selection:
  actions: [destroy, share, change_owner]
  segment: WatchListByCreatorWithoutMySelection

watch_list_user_shares:
  actions: [add_item, remove_item]
  segment: WatchListByUserShares

watch_list_group_shares:
  actions: [add_item, remove_item]
  segment: WatchListByGroupShares

watch_list_role_shares:
  actions: [add_item, remove_item]
  segment: WatchListByRoleShares

data_attribute_read:
  actions: read
  segment: DataAttributeAllowedForShow
  parameters:
    - - :attribute_not_disabled?
      - :overlay_attribute_visible?
      - :attribute_not_releasable?

data_attribute_edit:
  actions: edit
  segment: DataAttributeAllowedForEdit
  parameters:
    - - :attribute_not_included_in_publication_schedule?
      - :attribute_not_disabled?
      - :overlay_attribute_visible?
      - :attribute_not_external?
      - :attribute_tree_label_visible?

data_attribute_update:
  actions: update
  segment: DataAttributeAllowedForUpdate
  parameters:
    - - :attribute_not_included_in_publication_schedule?
      - :attribute_not_disabled?
      - :attribute_not_read_only?
      - :overlay_attribute_visible?
      - :attribute_not_external?
      - :attribute_tree_label_visible?

backend:
  actions: [read, settings, sortable]
  segment: SubjectByConditions
  parameters: :backend

filter:
  actions:
    - search
    - classification_trees
    - classification_tree
    - permanent_advanced
    - advanced
    - publication_date
  segment: SubjectByConditions
  parameters:
    - - :backend
      - :classification_tree
      - :publications
      - :subscriptions
      - :things
      - :collection

advanced_filter:
  actions: advanced_filter
  segment: AdvancedFilterExceptType
  parameters:
    - - :backend
      - :classification_tree
      - :publications
      - :subscriptions
      - :things
      - :collection

subscription_actions:
  actions: read
  segment: SubjectByConditions
  parameters:
    - - DataCycleCore::Subscription
      - :publication

user_actions:
  actions: [show, update]
  segment: SubjectByUserAndConditions
  parameters:
    - DataCycleCore::User
    - :id

classification_overview:
  actions: read
  segment: TreeLabelByVisibility
  parameters: classification_overview

auto_translate_feature:
  actions: [create, destroy]
  segment: SubjectByConditions
  parameters: :auto_translate

view_mode_feature:
  actions: [grid, list, tree, map]
  segment: SubjectByEnabledFeature
  parameters:
    - :view_mode
    - DataCycleCore::Feature::ViewMode
