---
- :data:
    :name: Datei
    :type: object
    :schema_type: CreativeWork
    :content_type: entity
    :boost: 10.0
    :features:
      :translatable:
        :allowed: true
    :api:
      :type: MediaObject
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :content_url:
        :label: Bild URL
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: content_url
          :parameters:
            :0: asset
        :api:
          :minimal: true
        :ui:
          :show:
            :disabled: true
      :asset:
        :label: Datei
        :type: asset
        :asset_type: asset
        :api:
          :disabled: true
      # schema.org: TEXT with KB/MB
      # data-cycle: Integer (Byte)
      :content_size:
        :label: Dateigröße
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Asset
          :method: file_size
          :parameters:
            :0: asset
      :file_format:
        :label: Dateiformat
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: file_format
          :parameters:
            :0: asset
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Datei"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
