---
- :data:
    :name: DataCycle - Video
    :type: object
    :content_type: entity
    :boost: 10.0
    :api:
      :type: VideoObject
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :caption:
        :label: Alt-Label
        :type: string
        :storage_location: translated_value
        :search: true
      :content_url:
        :label: Video URL
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: content_url
          :parameters:
            :0: asset
        :api:
          :minimal: true
        :ui:
          :show:
            :disabled: true
      :thumbnail_url:
        :label: Thumbnail URL
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Video
          :method: thumbnail_url
          :parameters:
            :0: asset
        :ui:
          :show:
            :disabled: true
        :api:
          :minimal: true
      :asset:
        :label: Datei
        :type: asset
        :asset_type: video
        :api:
          :disabled: true
      :width:
        :label: Breite
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Video
          :method: width
          :parameters:
            :0: asset
      :height:
        :label: Höhe
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Video
          :method: height
          :parameters:
            :0: asset
      :content_size:
        :label: Dateigröße
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Asset
          :method: file_size
          :parameters:
            :0: asset
      :file_format:
        :label: Dateiformat
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: file_format
          :parameters:
            :0: asset
      :duration:
        :label: Dauer
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Video
          :method: duration
          :parameters:
            :0: asset
      :video_frame_size:
        :label: Auslösung
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Video
          :method: frame_size
          :parameters:
            :0: asset
      :video_quality:
        :label: Qualität
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Video
          :method: quality
          :parameters:
            :0: asset
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "DataCycle - Video"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
