---
- :data:
    :name: title
    :type: mixin
    :properties:
      :legal_name:
        :label: Firmenname
        :type: string
        :storage_location: translated_value
        :search: true
        :validations:
          :min: 1
        :ui:
          :show:
            :disabled: true
        :api:
          :minimal: true