---
- :data:
    :name: content_classifications
    :type: mixin
    :properties:
      :output_channel:
        :label: Ausgabekanal
        :type: classification
        :classification_tree: Ausgabekanäle