:publication_schedule:
  :enabled: false

:download:
  :enabled: false

:overlay:
  :enabled: false
  :attribute_keys:
    - overlay

:releasable:
  :enabled: false
  :attribute_keys:
    - release_status_id
    - release_status_comment
  :classification_names:
    :valid: freigegeben
    :partner: beim Partner
    :review: in Review
    :archive: archiviert

:life_cycle:
  :enabled: false

:idea_collection:
  :enabled: false

:container:
  :enabled: false

:main_filter:
  :enabled: true
  :classification_alias_ids:
    - Inhaltstypen
  :autoload_last_filter: false

:advanced_filter:
  :enabled: true
  :classification_alias_ids: all
  :external_source: true
  :external_system: false
  :creator: true
  :classification_tree_ids: true
  :date_range: all
  :validity_period: true

:geocode:
  :enabled: false
  :attribute_keys:

:gpx_converter:
  :enabled: true

:external_media_archive:
  :enabled: false
  :template_mapping:
    :bild: image
    :video: video

:normalize:
  :enabled: false

:duplicate_content:
  :enabled: false

:image_optimizer:
  :enabled: true
  :config:
    :pngout: false
    :svgo: false
    :advpng: false
    :gifsicle:
      :careful: true
    :optipng:
      :strip: false
      :level: 1
    :jpegtran:
      :copy_chunks: true
    :jpegoptim:
      :strip: :comments
    :pngquant:
      :speed: 10

:duplicate_candidate:
  :enabled: false

:content_lock:
  :enabled: false
  :lock_length: <%= 30.minutes %>
  :lock_renew_before: <%= 5.minutes %>

:user_api:
  :only_config: true
  :expiration_time: <%= 24.hours %>
  :default_rank: 0
  :allowed_ranks:
    - 0
  :user_params:
    - email
    - given_name
    - family_name
    - default_locale
    - password
    - password_confirmation
  :issuer: datacycle.at

