---
- :data:
    :name: MediaLink
    :type: object
    :schema_type: CreativeWork
    :schema_ancestors:
      - CreativeWork
      - MediaObject
    :content_type: embedded
    :boost: 1.0
    :api:
      :type:
        - CreativeWork
        - MediaObject
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Name
        :type: string
        :storage_location: column
      :url:
        :label: Url
        :type: string
        :storage_location: translated_value
        :validations:
          :format: url
      :embed_url:
        :label: 'Url zur Verwendung in <embed>-Tags'
        :type: string
        :storage_location: translated_value
        :validations:
          :format: url
      :meta_data:
        :type: mixin
        :name: meta_data
