---
- :data:
    :name: Publikations-Plan
    :type: object
    :schema_type: CreativeWork
    :content_type: embedded
    :boost: 1.0
    :properties:
      :id:
        :label: id
        :type: key
      :publish_at:
        :label: Publikationsdatum
        :type: datetime
        :storage_location: value
        :validations:
          :format: date_time
        :ui:
          :edit:
            :type: date
            :options:
              :placeholder: tt.mm.jjjj
          :show:
            :type: date
        :advanced_search: true
      :output_channel:
        :label: Ausgabekanäle
        :type: classification
        :tree_label: Ausgabekanäle
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Publikations-Plan"
