---
- :data:
    :name: Video
    :type: object
    :schema_type: CreativeWork
    :content_type: entity
    :boost: 10.0
    :api:
      :type: VideoObject
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :caption:
        :label: Alt-Label
        :type: string
        :storage_location: translated_value
        :search: true
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :content_url:
        :label: Video URL
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: content_url
          :parameters:
            :0: asset
        :api:
          :minimal: true
        :ui:
          :show:
            :disabled: true
      :thumbnail_url:
        :label: Teaserbild
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Video
          :method: thumbnail_url
          :parameters:
            :0: asset
        :ui:
          :show:
            :partial: preview_image
        :api:
          :minimal: true
      :url:
        :label: Inhalt URL
        :type: string
        :storage_location: value
        :validations:
          :format: url
        :api:
          :name: sameAs
      :asset:
        :label: Datei
        :type: asset
        :asset_type: video
        :api:
          :disabled: true
      :width:
        :label: Breite
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Video
          :method: width
          :parameters:
            :0: asset
        :ui:
          :show:
            :options:
              :data-unit: px
        :api:
          :partial: property_value
          :type: QuantitativeValue
          :unit_text: pixel
          :unit_code: E37
          :transformation:
            :method: nest
            :name: width
      :height:
        :label: Höhe
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Video
          :method: height
          :parameters:
            :0: asset
        :ui:
          :show:
            :options:
              :data-unit: px
        :api:
          :partial: property_value
          :type: QuantitativeValue
          :unit_text: pixel
          :unit_code: E37
          :transformation:
            :method: nest
            :name: height
      # schema.org: TEXT with KB/MB
      # data-cycle: Integer (Byte)
      :content_size:
        :label: Dateigröße
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Asset
          :method: file_size
          :parameters:
            :0: asset
      :file_format:
        :label: Dateiformat
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Asset
          :method: file_format
          :parameters:
            :0: asset
      :duration:
        :label: Dauer
        :storage_location: value
        :type: computed
        :compute:
          :type: number
          :module: Utility::Compute::Video
          :method: duration
          :parameters:
            :0: asset
        :ui:
          :show:
            :options:
              :data-unit: sec
        :api:
          :partial: duration
          :format:
            :append: S
            :prepend: PT
      :video_frame_size:
        :label: Auslösung
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Video
          :method: frame_size
          :parameters:
            :0: asset
      :video_quality:
        :label: Qualität
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Video
          :method: quality
          :parameters:
            :0: asset
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Video"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
