---
- :data:
    :name: Zitat
    :type: object
    :schema_type: CreativeWork
    :content_type: embedded
    # schema.org AdditionalProperties
    # schema.org pending: http://schema.org/Quotation
    :properties:
      :id:
        :label: id
        :type: key
      :text:
        :label: text
        :type: string
        :storage_location: translated_value
        :validations:
          :min: 1
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: full
      :image:
        :label: Bilder
        :type: linked
        :template_name: Bild
        :validations:
          :max: 1
      :author:
        :label: "Zitat von"
        :type: linked
        :template_name: Person
        :validations:
          :max: 1
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Zitat"
