---
- :data:
    :name: PlaceOverlay
    :type: object
    :content_type: embedded
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: translated_value
        :search: true
        :validations:
          :min: 1
      :description:
        :label: Beschreibung
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: full
      :image:
        :label: Bilder
        :type: linked
        :linked_table: creative_works
        :template_name: Bild
      :opening_hours_specification:
        :label: Öffnungszeit
        :type: embedded
        :linked_table: creative_works
        :template_name: Öffnungszeit
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Overlay"
      :meta_data:
        :type: mixin
        :name: meta_data