---
- :data:
    :name: feratel_categories
    :type: mixin
    :properties:
      :holiday_themes:
        :label: Feratel - Urlaubsthemen
        :type: classification
        :tree_label: Feratel - Urlaubsthemen
      :accommodation_categories:
        :label: Feratel - Unterkunftsarten
        :type: classification
        :tree_label: Feratel - Unterkunftsarten
      :feratel_classifications:
        :label: Feratel - Unterkunftsklassifizierungen
        :type: classification
        :tree_label: Feratel - Unterkunftsklassifizierungen
      :stars:
        :label: Feratel - Sterne
        :type: classification
        :tree_label: Feratel - Sterne
      :feratel_owners:
        :label: Feratel - Inhaber
        :type: classification
        :tree_label: Feratel - Inhaber