---
- :data:
    :name: feratel_resort
    :type: mixin
    :properties:
      :feratel_resort_status:
        :label: Feratel - Resort - Status
        :type: classification
        :tree_label: Feratel - Resort - Status
        :ui:
          :show:
            :content_area: header
      :feratel_resort_type:
        :label: Feratel - Resort - Type
        :type: classification
        :tree_label: Feratel - Resort - Type
        :ui:
          :show:
            :content_area: header
