---
- :data:
    :name: google
    :type: mixin
    :properties:
      :google_tags:
        :label: GooglePlaces - Tags
        :type: classification
        :tree_label: GooglePlaces - Tags
        :ui:
          :show:
            :content_area: header
