---
- :data:
    :name: outdoor_active_categories
    :type: mixin
    :properties:
      :frontend_type:
        :label: Frontend-Typ
        :type: classification
        :tree_label: OutdoorActive - FrontendTypes
      :categories:
        :label: Kategorien
        :type: classification
        :tree_label: OutdoorActive - Kategorien
      :outdoor_active_tags:
        :label: OutdoorActive - Tags
        :type: classification
        :tree_label: OutdoorActive - Tags
      :regions:
        :label: Regionen
        :type: classification
        :tree_label: OutdoorActive - Regionen
      :source:
        :label: Quelle
        :type: classification
        :tree_label: OutdoorActive - Quellen
