---
- :data:
    :name: xamoom
    :type: mixin
    :properties:
      :xamoom_tags:
        :label: Xamoom - Tags
        :type: classificationTreeLabel
        :type_name: Xamoom - Tags
        :storage_location: classification_relation