---
- :data:
    :name: validity_period
    :type: mixin
    :properties:
      :validity_period:
        :label: Gültigkeitszeitraum
        :type: object
        :storage_location: metadata
        :validations:
          :daterange:
            :from: valid_from
            :to: valid_until
        :editor:
          :options:
            :class: daterange
        :properties:
          :valid_from:
            :label: Gültigkeit
            :type: string
            :storage_type: string
            :storage_location: metadata
            :validations:
              :format: date_time
            :editor:
              :type: date
              :options:
                :data-type: datepicker
                :data-validate: daterange
                :placeholder: tt.mm.jjjj
          :valid_until:
            :label: bis
            :type: string
            :storage_type: string
            :storage_location: metadata
            :validations:
              :format: date_time
            :editor:
              :type: date
              :options:
                :data-type: datepicker
                :data-validate: daterange
                :placeholder: tt.mm.jjjj