---
- :data:
    :name: POI
    :type: object
    :content_type: entity
    :boost: 10.0
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :name:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :options:
            :data-validate: text
      :opening_hours_specification:
        :label: Öffnungszeit
        :type: object
        :storage_location: creative_works
        :delete: true
        :name: Öffnungszeit
        :editor:
          :type: embeddedObject
      :postal_address:
        :type: mixin
        :name: postal_address
      :geo:
        :type: mixin
        :name: geo
      :contact_info:
        :type: mixin
        :name: contact_info
      :description:
        :label: Beschreibung
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :editor:
          :type: input
      :text:
        :label: Text
        :type: string
        :storage_type: text
        :storage_location: content
        :search: true
        :editor:
          :type: quillEditor
          :options:
            :data-size: basic
      :primary_image:
        :label: Hauptbild
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: string
        :storage_location: metadata
        :validations:
          :max: 1
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :image:
        :label: Bilder
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: string
        :storage_location: metadata
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "POI"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties