---
- :data:
    :name: Tour
    :type: object
    :content_type: entity
    :permissions:
      :read_write: true
    :boost: 10.0
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :name:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :options:
            :data-validate: text
      :description:
        :label: Beschreibung
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :editor:
          :options:
            :readonly: true
      :text:
        :label: Text
        :type: string
        :storage_type: text
        :storage_location: content
        :search: true
        :editor:
          :type: quillEditor
          :options:
            :data-size: basic
      :primary_image:
        :label: Hauptbild
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: string
        :storage_location: metadata
        :validations:
          :max: 1
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :image:
        :label: Bilder
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: string
        :storage_location: metadata
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :outdoor_active:
        :type: mixin
        :name: outdoor_active
      :outdoor_active_categories:
        :type: mixin
        :name: outdoor_active_categories
      :start_location:
        :label: Startkoordinaten
        :type: geographic
        :storage_type: geographic
        :storage_location: metadata
      :tour:
        :label: Route
        :type: geographic
        :storage_type: geographic
        :storage_location: metadata
      :directions_public_transport:
        :label: Anfahrt mit öffentlichen Verkehrsmitteln
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :editor:
          :type: input
      :instructions:
        :label: Wegbeschreibung
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :editor:
          :type: input
      :safety_instructions:
        :label: Sicherheitshinweis
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :editor:
          :type: input
      :equipment:
        :label: Ausrüstung
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :editor:
          :type: input
      :suggestion:
        :label: Tipps
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :editor:
          :type: input
      :additional_information:
        :label: Zusatzinformation
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :editor:
          :type: input
      :ascent:
        :label: Aufstieg (m)
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :descent:
        :label: Abstieg (m)
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :min_altitude:
        :label: Minimale Seehöhe (m)
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :max_altitude:
        :label: Maximale Seehöhe (m)
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :length:
        :label: Länge (m)
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :duration:
        :label: Dauer (min)
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :condition_rating:
        :label: Bewertung - Kondition
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :difficulty_rating:
        :label: Bewertung - Schwierigkeit
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :experience_rating:
        :label: Bewertung - Erlebnis
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :landscape_rating:
        :label: Bewertung - Landschaft
        :type: number
        :storage_type: number
        :storage_location: metadata
        :editor:
          :type: input
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Tour"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data