- Inhaltstypen:
  - $$Test-Template
  - $$Asset:
    - $$Bild
  - $$Ort:
    - $$Örtlichkeit
  - $$Person
# embedded
  - $$Zitat
  - $$Overlay

- Geschlecht:
  - Männlich
  - Weiblich

- Themenbereiche:
  - Test-Thema 1
  - Test-Thema 2
  - Test-Thema 3

- Ausgabekanäle:
  - Ausgabekanal 1
  - Ausgabekanal 2
  - Ausgabekanal 3
