---
- :data:
    :name: Schneehöhe - Messpunkt
    :type: object
    :schema_type: Place
    :content_type: embedded
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Titel
        :type: string
        :storage_location: column
        :api:
          :minimal: true
      :elevation:
        :label: Meereshöhe (m)
        :type: number
        :storage_location: column
        :validations:
          :format: float
        :api:
          :transformation:
            :method: nest
            :name: geo
            :type: GeoCoordinates
          :minimal: true
      :depth_of_snow:
        :label: Schneehöhe
        :type: number
        :storage_location: value
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
        :validations:
          :format: float
        :ui:
          :edit:
            :options:
              :data-unit: cm
          :show:
            :options:
              :data-unit: cm
      :depth_of_fresh_snow:
        :label: Neuschnee
        :type: number
        :storage_location: value
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
        :validations:
          :format: float
        :ui:
          :edit:
            :options:
              :data-unit: cm
          :show:
            :options:
              :data-unit: cm
      :condition_weather:
        :label: "Wetter - Meldung"
        :type: classification
        :tree_label: "Bergfex - Wetter - Meldung"
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Schneehöhe - Messpunkt"
      :meta_data:
        :type: mixin
        :name: meta_data
