---
- :data:
    :name: Skigebiet
    :type: object
    :schema_type: Place
    :content_type: entity
    :boost: 100.0
    :features:
      :overlay:
        :allowed: true
      :translatable:
        :allowed: true
    :api:
      :type: SkiResort
    :properties:
      :id:
        :label: id
        :type: key
      :overlay:
        :label: Overlay
        :type: embedded
        :template_name: SnowResortOverlay
        :validations:
          :max: 1
      :title:
        :type: mixin
        :name: title
      :bergfex_status_icon:
        :label: "Status-Icon"
        :type: classification
        :tree_label: "Bergfex - Status - Icon"
        :external: true
        :ui:
          :show:
            :content_area: header
      :date_time_updated_at:
        :label: Zuletzt aktualisiert
        :type: datetime
        :storage_location: value
        :validations:
          :format: date_time
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
        :ui:
          :edit:
            :type: datetime
            :options:
              :class: single_date
              :placeholder: "tt.mm.jjjj --:--"
      :date_last_snowfall:
        :label: Letzter Schneefall
        :type: datetime
        :storage_location: value
        :validations:
          :format: date_time
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
        :ui:
          :edit:
            :type: date
            :options:
              :class: single_date
              :placeholder: "tt.mm.jjjj"
          :show:
            :type: date
      :lifts:
        :label: Lifte
        :type: object
        :storage_location: value
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
        :properties:
          :value:
            :label: Geöffnete Lifte
            :type: number
            :storage_location: value
            :validations:
              :format: integer
          :max_value:
            :label: Lifte gesamt
            :type: number
            :storage_location: value
            :validations:
              :format: integer
      :slopes:
        :label: Pistenlänge
        :type: object
        :storage_location: value
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
        :properties:
          :value:
            :label: Pistenlänge, geöffnete Pisten
            :type: number
            :storage_location: value
            :validations:
              :format: float
          :max_value:
            :label: Max Pistenlänge
            :type: number
            :storage_location: value
            :validations:
              :format: float
      :count_open_slopes:
        :label: Pisten
        :type: object
        :storage_location: value
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
        :properties:
          :value:
            :label: Geöffnete Pisten
            :type: number
            :storage_location: value
            :validations:
              :format: integer
          :max_value:
            :label: Pisten gesamt
            :type: number
            :storage_location: value
            :validations:
              :format: integer
      :length_nordic_classic:
        :label: Loipenlänge Nordisch Klassisch
        :type: number
        :storage_location: value
        :validations:
          :format: float
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
      :length_nordic_skating:
        :label: Loipenlänge Nordisch Skating
        :type: number
        :storage_location: value
        :validations:
          :format: float
        :api:
          :partial: property_value
          :type: PropertyValue
          :transformation:
            :method: combine
            :name: additionalProperty
      :opening_hours_specification:
        :label: Öffnungszeit
        :type: embedded
        :template_name: Öffnungszeit
      :addons:
        :label: Addons
        :type: embedded
        :template_name: Skigebiet - Addon
        :api:
          :name: amenityFeature
      :geo:
        :type: mixin
        :name: geo
      :snow_report:
        :label: Schneehöhe - Messpunkt
        :type: embedded
        :template_name: Schneehöhe - Messpunkt
        :api:
          :name: containsPlace
          :partial: to_linked
      :url:
        :label: Link
        :type: string
        :storage_location: translated_value
        :api:
          :name: sameAs
      :condition_avalanche_warning_level:
        :label: "Lawinenwarnlevel"
        :type: classification
        :tree_label: "Bergfex - Lawinenwarnlevel"
        :external: true
        :ui:
          :show:
            :content_area: header
      :condition_nordic_classic:
        :label: "NordicClassic - Meldung"
        :type: classification
        :tree_label: "Bergfex - NordicClassic - Meldung"
        :external: true
        :ui:
          :show:
            :content_area: header
      :condition_nordic_skating:
        :label: "NordicSkating - Meldung"
        :type: classification
        :tree_label: "Bergfex - NordicClassic - Meldung"
        :external: true
        :ui:
          :show:
            :content_area: header
      :condition_run_to_valley:
        :label: "Talfahrt - Meldung"
        :type: classification
        :tree_label: "Bergfex - Talfahrt - Meldung"
        :external: true
        :ui:
          :show:
            :content_area: header
      :condition_slopes:
        :label: "Pisten - Meldung"
        :type: classification
        :tree_label: "Bergfex - Pisten - Meldung"
        :external: true
        :ui:
          :show:
            :content_area: header
      :condition_snow:
        :label: "Schnee - Meldung"
        :type: classification
        :tree_label: "Bergfex - Schnee - Meldung"
        :external: true
        :ui:
          :show:
            :content_area: header
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Skigebiet"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
