---
- :data:
    :name: media_archive
    :type: mixin
    :properties:
      :mandatory_license:
        :label: Copyright Nennung verpflichtend
        :type: boolean
        :storage_location: value
      :comment:
        :label: Kommentar
        :type: string
        :storage_location: translated_value
        :search: true
      :source:
        :label: Erhalten von
        :type: string
        :storage_location: value
      :image_id:
        :label: Bildnummer
        :type: string
        :storage_location: value
      :visibility:
        :label: Sichtbarkeit
        :type: string
        :storage_location: value
      :restrictions:
        :label: Einschränkungen
        :type: string
        :storage_location: value
