---
- :data:
    :name: media_archive_categories
    :type: mixin
    :properties:
      :access:
        :label: Rechte/Einsatzgebiet
        :type: classificationTreeLabel
        :type_name: Rechte
        :storage_location: classification_relation
        :editor:
          :type: input
      :keywords:
        :label: Tags
        :type: classificationTreeLabel
        :type_name: MediaArchive - Tags
        :storage_location: classification_relation
        :editor:
          :type: input