---
- :data:
    :name: tags
    :type: mixin
    :properties:
      :tags:
        :label: Tags
        :type: classification
        :tree_label: Tags
        :ui:
          :show:
            :content_area: header
      :keywords_medienarchive:
        :label: MediaArchive - Tags
        :type: classification
        :tree_label: MediaArchive - Tags
        :ui:
          :show:
            :content_area: header
