---
- :data:
    :name: tags
    :type: mixin
    :properties:
      :tags:
        :label: Tags
        :type: classification
        :tree_label: Tags
        :ui:
          :show:
            :content_area: header
      :keywords_medienarchive:
        :label: MediaArchive - Tags
        :type: classification
        :tree_label: MediaArchive - Tags
        :external: true
        :ui:
          :show:
            :content_area: header
      :hrs_image_categories:
        :label: HRS - Image-Categories
        :type: classification
        :tree_label: HRS - Image-Categories
        :external: true
        :ui:
          :show:
            :content_area: header            
