---
- :data:
    :name: tags
    :type: mixin
    :properties:
      :keywords:
        :label: Tags
        :type: classificationTreeLabel
        :type_name: Tags
        :storage_location: classification_relation
        :editor:
          :type: input
      :keywords_medienarchive:
        :label: MediaArchive - Tags
        :type: classificationTreeLabel
        :type_name: MediaArchive - Tags
        :storage_location: classification_relation
        :editor:
          :type: input
