---
name: DataCycle Basic
identifier: data-cycle-base
credentials:
  host: HOST
  end_point: ENDPOINT
  token: TOKEN
config:
  download_config:
    things:
      sorting: 1
      source_type: things
      endpoint: DataCycleCore::Generic::DcSync::Endpoint
      download_strategy: DataCycleCore::Generic::DcSync::Download
  import_config:
    things:
      sorting: 1
      source_type: things
      import_strategy: DataCycleCore::Generic::DcSync::Import
