---
name: DataCycle Basic
identifier: data-cycle-base
credentials:
  host: https://basic.datacycle.at
  end_point: sync_api/v1/endpoints/41e72bcc-021a-40bf-9ab3-195219425506
  token: 38a88193543ef6329e98efd3c2c22a03
config:
  download_config:
    things:
      sorting: 1
      source_type: things
      endpoint: DataCycleCore::Generic::DcSync::Endpoint
      download_strategy: DataCycleCore::Generic::DcSync::Download
  import_config:
    things:
      sorting: 1
      source_type: things
      import_strategy: DataCycleCore::Generic::DcSync::Import
