---
name: austria.info
credentials:
  host: http://test.com
  token: xxxxxxxxx
  api_version: 4
  api_subversion:
default_options:
  export:
    external_url: 'https://cms.austria.info/admin/app/sonatapagepage/%{external_key}/edit'
config:
  api_strategy: DataCycleCore::Generic::ExternalLink::Webhook
