---
name: austria.info
credentials:
  host: HOST
  token: TOKE
  api_version: API_VERSION
  api_subversion: API_SUBVERSION
default_options:
  export:
    external_url: EXTERNAL_URL
config:
  api_strategy: DataCycleCore::Generic::ExternalLink::Webhook
