---
name: Feratel Identity Server
credentials:
  host: https://apiidentitytest.deskline.net
  grant_type: password
  username: PixelPointAdmin
  password: orplW4juKe
  external_source: Feratel Identity Server
  client_options:
    identifier: data_cycle_test
    secret: secret
    host: identitytest.deskline.net
    scheme: https
    port: 443
    authorization_endpoint: /connect/authorize
    token_endpoint: /connect/token
config:
  push_config:
    allowed_models:
      - DataCycleCore::User
    endpoint: DataCycleCore::Export::FeratelIdentityServer::Endpoint
    create:
      strategy: DataCycleCore::Export::FeratelIdentityServer::Create
    update:
      strategy: DataCycleCore::Export::FeratelIdentityServer::Update
    delete:
      strategy: DataCycleCore::Export::FeratelIdentityServer::Delete
