---
name: Feratel Kärnten
credentials:
  pos_code: KAERNTEN
  company_code: PI78XE567L
  range_code: RG
  range_id: 4dac9143-899b-4938-ae23-53941e7c76ad
  sales_channel_id: BB556229-E7B1-4F21-9C6A-2BEA7120BF5A
  db_code: KTN
config:
  download_config:
    initial_locations:
      sorting: 1
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: locations
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    locations:
      sorting: 2
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: locations
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    categories:
      sorting: 3
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: categories
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    holiday_themes:
      sorting: 4
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: holiday_themes
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    facilities:
      sorting: 5
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: facilities
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    facility_groups:
      sorting: 6
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: facility_groups
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    infrastructure_topics:
      sorting: 7
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_topics
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    infrastructure_types:
      sorting: 8
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_types
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTypes
    custom_attributes:
      sorting: 9
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: custom_attributes
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadCategories
    stars:
      sorting: 10
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: stars
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadCategories
    classifications:
      sorting: 11
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: classifications
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadCategories
    rating_questions:
      sorting: 12
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: rating_questions
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    additional_service_providers:
      sorting: 20
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: additional_service_providers
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
    infrastructure_items:
      sorting: 30
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_items
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
    events:
      sorting: 40
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: events
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
    packages:
      sorting: 50
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: packages
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadPackages
    package_containers:
      sorting: 60
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: package_containers
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadPackages
    accommodations:
      sorting: 70
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: accommodations
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
    mark_deleted_accommodations:
      sorting: 100
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: accommodations
      read_type: locations
      endpoint_method: mark_deleted_accommodations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
      delete_reason: 'Published from Feratel delete endpoint for Accommodations.'
    # mark_deleted_additional_service_providers:
    #   sorting: 101
    #   endpoint: DataCycleCore::Generic::Feratel::Endpoint
    #   source_type: additional_service_providers
    #   read_type: locations
    #   endpoint_method: mark_deleted_accommodations
    #   location_range_codes: ['RG']
    #   download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
    mark_deleted_events:
      sorting: 110
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: events
      read_type: locations
      endpoint_method: mark_deleted_events
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
      delete_reason: 'Published from Feratel delete endpoint for Events.'
    mark_deleted_infrastructure_items:
      sorting: 120
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_items
      read_type: locations
      endpoint_method: mark_deleted_infrastructure_items
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
      delete_reason: 'Published from Feratel delete endpoint for InfrastructureItems.'
  import_config:
    content_score_asp:
      sorting: 1
      source_type: additional_service_providers
      tree_label: Feratel - ContentScore
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'QualityDetails.ContentScore'
      tag_id_path: 'QualityDetails.ContentScore.text'
      tag_name_path: 'QualityDetails.ContentScore.text'
      external_id_prefix: 'Feratel - ContentScore - '
      external_id_hash_method: 'round'
      tag_name_function: 'round'
    content_score_ii:
      sorting: 2
      source_type: infrastructure_items
      tree_label: Feratel - ContentScore
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'QualityDetails.ContentScore'
      tag_id_path: 'QualityDetails.ContentScore.text'
      tag_name_path: 'QualityDetails.ContentScore.text'
      external_id_prefix: 'Feratel - ContentScore - '
      external_id_hash_method: 'round'
      tag_name_function: 'round'
    content_score_a:
      sorting: 3
      source_type: accommodations
      tree_label: Feratel - ContentScore
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'QualityDetails.ContentScore'
      tag_id_path: 'QualityDetails.ContentScore.text'
      tag_name_path: 'QualityDetails.ContentScore.text'
      external_id_prefix: 'Feratel - ContentScore - '
      external_id_hash_method: 'round'
      tag_name_function: 'round'
    feratel_mealcodes_accommodations:
      sorting: 4
      source_type: accommodations
      tree_label: Feratel - Verpflegungs Kürzel
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Services.Service.Products.Product'
      tag_id_path: 'Services.Service.Products.Product.Price.StandardMealCode'
      tag_name_path: 'Services.Service.Products.Product.Price.StandardMealCode'
      external_id_prefix: 'Feratel - Verpflegungs Kürzel - '
      locales: [de]
    feratel_mealcodes_packages:
      sorting: 5
      source_type: packages
      tree_label: Feratel - Verpflegungs Kürzel
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Details.PackageCategories.PackageCategory'
      tag_id_path: 'Details.PackageCategories.PackageCategory.MealCode'
      tag_name_path: 'Details.PackageCategories.PackageCategory.MealCode'
      external_id_prefix: 'Feratel - Verpflegungs Kürzel - '
      locales: [de]
    categories:
      sorting: 10
      source_type: categories
      tree_label: Feratel - Unterkunftsarten
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
      locales: [de]
    feratel_owners:
      sorting: 11
      source_type: accommodations
      tree_label: Feratel - Inhaber
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Details.DataOwner.text'
      tag_name_path: 'Details.DataOwner.text'
      external_id_prefix: 'OWNER:'
      external_id_hash_method: 'MD5'
      locales: [de]
    feratel_infrastructure_owners:
      sorting: 12
      source_type: infrastructure_items
      tree_label: Feratel - Inhaber
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Details.DataOwner.text'
      tag_name_path: 'Details.DataOwner.text'
      external_id_prefix: 'OWNER:'
      external_id_hash_method: 'MD5'
      locales: [de]
    facilities:
      sorting: 13
      source_type: facilities
      tree_label: Feratel - Ausstattungsmerkmale
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
      source_filter:
        'dump.de.Type':
          '$ne': 'Event'
    facilities_count:
      sorting: 14
      source_type: accommodations
      tree_label: Feratel - Ausstattungsmerkmale
      import_strategy: DataCycleCore::Generic::Feratel::ImportFacilitiesCount
    holiday_themes:
      sorting: 15
      source_type: holiday_themes
      tree_label: Feratel - Urlaubsthemen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
      locales: [de]
    infrastructure_types:
      sorting: 16
      source_type: infrastructure_types
      tree_label: Feratel - Infrastrukturtypen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Type'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: 'Feratel - Infrastrukturtyp - '
      locales: [de]
    infrastructure_topics:
      sorting: 17
      source_type: infrastructure_topics
      tree_label: Feratel - Infrastrukturklassifizierungen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
      locales: [de]
    classifications:
      sorting: 18
      source_type: classifications
      tree_label: Feratel - Unterkunftsklassifizierungen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
      locales: [de]
    stars:
      sorting: 19
      source_type: stars
      tree_label: Feratel - Sterne
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
      locales: [de]
    product_types:
      sorting: 20
      source_type: accommodations
      tree_label: Feratel - Produktarten
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Services.Service.Products.Product'
      tag_id_path: 'Services.Service.Products.Product.Details.ProductType.text'
      tag_name_path: 'Services.Service.Products.Product.Details.ProductType.text'
      external_id_prefix: 'Feratel - Produktart - '
      locales: [de]
    accommodation_type:
      sorting: 21
      source_type: accommodations
      tree_label: Feratel - Unterkunftstypen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Services.Service.Products.Product'
      tag_id_path: 'Services.Service.Products.Product.Details.AccommodationType.text'
      tag_name_path: 'Services.Service.Products.Product.Details.AccommodationType.text'
      external_id_prefix: 'Feratel - Unterkunftstype - '
      locales: [de]
    accommodation_type_additional:
      sorting: 22
      source_type: accommodations
      tree_label: Feratel - Unterkunftstypen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'AdditionalServices.AdditionalService.Products.Product'
      tag_id_path: 'AdditionalServices.AdditionalService.Products.Product.Details.AccommodationType.text'
      tag_name_path: 'AdditionalServices.AdditionalService.Products.Product.Details.AccommodationType.text'
      external_id_prefix: 'Feratel - Unterkunftstype - '
      locales: [de]
    locations:
      sorting: 23
      source_type: locations
      tree_label: Feratel - Orte
      import_strategy: DataCycleCore::Generic::Feratel::ImportLocations
    facility_groups_events:
      sorting: 24
      source_type: facilities
      tree_label: Feratel - Merkmale - Events
      import_strategy: DataCycleCore::Generic::Feratel::ImportFacilityGroups
      source_filter:
        'dump.de.Active': 'true'
        'dump.de.ValueType': 'YesNo'
        '$or':
          - 'dump.de.Type': 'Event'
    infrastructure_items_w_o_gastro:
      sorting: 40
      source_type: infrastructure_items
      source_filter:
        'dump.de.Details.Topics.Type':
          :'$ne': '1'
        'dump.de.Details.Active.text': 'true'
      import_strategy: DataCycleCore::Generic::Feratel::ImportInfrastructure
      transformations:
        image:
          template: Bild
        infrastructure:
          template: POI
#    infrastructure_items:
#      sorting: 20
#      source_type: infrastructure_items
#      import_strategy: DataCycleCore::Generic::Feratel::ImportInfrastructure
#      transformations:
#        image:
#          template: Bild
#        infrastructure:
#          template: POI
    # additional_service_providers:
    #   source_type: DataCycleCore::Generic::SourceType::AdditionalServiceProvider
    #   target_type: DataCycleCore::Thing
    #   image_template: Bild
    #   data_template: POI
    #   import_strategy: DataCycleCore::Generic::Feratel::ImportPlaces
    packages:
      sorting: 42
      source_type: packages
      import_strategy: DataCycleCore::Generic::Feratel::ImportPackages
    accommodations:
      sorting: 44
      source_type: accommodations
      import_strategy: DataCycleCore::Generic::Feratel::ImportAccommodations
      transformations:
        image:
          template: Bild
        place:
          template: Unterkunft
    delete_accommodations:
      sorting: 46
      source_type: accommodations
      import_strategy: DataCycleCore::Generic::Common::DeleteContentsSafe
      external_key_path: 'Id'
    events:
      sorting: 48
      source_type: events
      import_strategy: DataCycleCore::Generic::Feratel::ImportEvents
      transformations:
        image:
          template: Bild
        place:
          template: Örtlichkeit
        event:
          template: Event
    delete_events:
      sorting: 49
      import_strategy: DataCycleCore::Generic::Common::DeleteContentsSafe
      source_type: events
      external_key_path: 'Id'
