---
name: Feratel VCloud
credentials:
  - pos_code: LECH
    company_code: D474CYC1E
    range_code: RG
    range_id: B44EB81C-D743-49BE-80B0-85755EF600D4
    sales_channel_id: BB556229-E7B1-4F21-9C6A-2BEA7120BF5A
  - pos_code: MONTAFON
    company_code: D474CYC1E
    range_code: RG
    range_id: 6C23D36D-BE29-414F-B550-B79518686C5D
    sales_channel_id: BB556229-E7B1-4F21-9C6A-2BEA7120BF5A
  - pos_code: BLUDENZ
    company_code: D474CYC1E
    range_code: RG
    range_id: 0be26b7e-e564-47cc-99ac-cce16e37d95b
    sales_channel_id: BB556229-E7B1-4F21-9C6A-2BEA7120BF5A
  - pos_code: KLEINWALS
    company_code: D474CYC1E
    range_code: RG
    range_id: 8cdc270e-6019-4536-a13f-0f8d5a024170
    sales_channel_id: BB556229-E7B1-4F21-9C6A-2BEA7120BF5A
config:
  download_config:
    initial_locations:
      sorting: 1
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: locations
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    categories:
      sorting: 2
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: categories
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    locations:
      sorting: 3
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: locations
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    holiday_themes:
      sorting: 4
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: holiday_themes
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    facilities:
      sorting: 5
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: facilities
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    facility_groups:
      sorting: 6
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: facility_groups
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    infrastructure_topics:
      sorting: 7
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_topics
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    infrastructure_types:
      sorting: 8
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_types
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTypes
    custom_attributes:
      sorting: 9
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: custom_attributes
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadCategories
    stars:
      sorting: 10
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: stars
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadCategories
    classifications:
      sorting: 11
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: classifications
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadCategories
    rating_questions:
      sorting: 12
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: rating_questions
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    additional_service_providers:
      sorting: 13
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: additional_service_providers
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
    infrastructure_items:
      sorting: 14
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_items
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
    events:
      sorting: 15
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: events
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
      locales: ['de', 'en']
    packages:
      sorting: 16
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: packages
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadPackages
      locales: ['de', 'en']
    package_containers:
      sorting: 17
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: package_containers
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadPackages
      locales: ['de', 'en']
    accommodations:
      sorting: 18
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: accommodations
      read_type: locations
      download_strategy: DataCycleCore::Generic::Feratel::DownloadContents
      locales: ['de', 'en']
    hot_spots:
      sorting: 21
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: hot_spots
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    marketing_groups:
      sorting: 22
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: marketing_groups
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    rating_visitors:
      sorting: 23
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: rating_visitors
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    service_codes:
      sorting: 24
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: service_codes
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedServiceCodes
    shop_item_groups:
      sorting: 25
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: shop_item_groups
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    fallback_languages:
      sorting: 28
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: fallback_languages
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadLanguages
    link_types:
      sorting: 29
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: link_types
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    handicap_groups:
      sorting: 30
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: handicap_groups
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    handicap_types:
      sorting: 31
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: handicap_types
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    handicap_facility_groups:
      sorting: 32
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: handicap_facility_groups
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    handicap_facilities:
      sorting: 33
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: handicap_facilities
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadTranslatedCategories
    visitor_tax:
      sorting: 34
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: visitor_tax
      read_type: locations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadCodes
      locales: [de]
    mark_deleted_accommodations:
      sorting: 100
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: accommodations
      read_type: locations
      endpoint_method: mark_deleted_accommodations
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
    # mark_deleted_additional_service_providers:
    #   sorting: 101
    #   endpoint: DataCycleCore::Generic::Feratel::Endpoint
    #   source_type: additional_service_providers
    #   read_type: locations
    #   endpoint_method: mark_deleted_accommodations
    #   location_range_codes: ['RG']
    #   download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
    mark_deleted_events:
      sorting: 110
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: events
      read_type: locations
      endpoint_method: mark_deleted_events
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
    mark_deleted_infrastructure_items:
      sorting: 120
      endpoint: DataCycleCore::Generic::Feratel::Endpoint
      source_type: infrastructure_items
      read_type: locations
      endpoint_method: mark_deleted_infrastructure_items
      location_range_codes: ['RG']
      download_strategy: DataCycleCore::Generic::Feratel::DownloadMarkDeleted
  import_config:
#    content_score_asp:
#      sorting: 1
#      source_type: additional_service_providers
#      tree_label: Feratel - ContentScore
#      import_strategy: DataCycleCore::Generic::Common::ImportTags
#      tag_path: 'QualityDetails.ContentScore'
#      tag_id_path: 'QualityDetails.ContentScore.text'
#      tag_name_path: 'QualityDetails.ContentScore.text'
#      external_id_prefix: 'Feratel - ContentScore - '
#      external_id_hash_method: 'round'
#      tag_name_function: 'round'
#    content_score_ii:
#      sorting: 2
#      source_type: infrastructure_items
#      tree_label: Feratel - ContentScore
#      import_strategy: DataCycleCore::Generic::Common::ImportTags
#      tag_path: 'QualityDetails.ContentScore'
#      tag_id_path: 'QualityDetails.ContentScore.text'
#      tag_name_path: 'QualityDetails.ContentScore.text'
#      external_id_prefix: 'Feratel - ContentScore - '
#      external_id_hash_method: 'round'
#      tag_name_function: 'round'
#    content_score_a:
#      sorting: 3
#      source_type: accommodations
#      tree_label: Feratel - ContentScore
#      import_strategy: DataCycleCore::Generic::Common::ImportTags
#      tag_path: 'QualityDetails.ContentScore'
#      tag_id_path: 'QualityDetails.ContentScore.text'
#      tag_name_path: 'QualityDetails.ContentScore.text'
#      external_id_prefix: 'Feratel - ContentScore - '
#      external_id_hash_method: 'round'
#      tag_name_function: 'round'
    feratel_mealcodes_accommodations:
      sorting: 4
      source_type: accommodations
      tree_label: Feratel - Verpflegungs Kürzel
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Services.Service.Products.Product'
      tag_id_path: 'Services.Service.Products.Product.Price.StandardMealCode'
      tag_name_path: 'Services.Service.Products.Product.Price.StandardMealCode'
      external_id_prefix: 'Feratel - Verpflegungs Kürzel - '
      locales: [de]
    feratel_mealcodes_packages:
      sorting: 5
      source_type: packages
      tree_label: Feratel - Verpflegungs Kürzel
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Details.PackageCategories.PackageCategory'
      tag_id_path: 'Details.PackageCategories.PackageCategory.MealCode'
      tag_name_path: 'Details.PackageCategories.PackageCategory.MealCode'
      external_id_prefix: 'Feratel - Verpflegungs Kürzel - '
      locales: [de]
    categories:
      sorting: 10
      source_type: categories
      tree_label: Feratel - Unterkunftsarten
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
    feratel_owners:
      sorting: 11
      source_type: accommodations
      tree_label: Feratel - Inhaber
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Details.DataOwner.text'
      tag_name_path: 'Details.DataOwner.text'
      external_id_prefix: 'OWNER:'
      external_id_hash_method: 'MD5'
    feratel_infrastructure_owners:
      sorting: 12
      source_type: infrastructure_items
      tree_label: Feratel - Inhaber
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Details.DataOwner.text'
      tag_name_path: 'Details.DataOwner.text'
      external_id_prefix: 'OWNER:'
      external_id_hash_method: 'MD5'
    facilities:
      sorting: 13
      source_type: facilities
      tree_label: Feratel - Ausstattungsmerkmale
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
    facilities_count:
      sorting: 14
      source_type: accommodations
      tree_label: Feratel - Ausstattungsmerkmale
      import_strategy: DataCycleCore::Generic::Feratel::ImportFacilitiesCount
    facilities_count_events:
      sorting: 15
      source_type: events
      tree_label: Feratel - Ausstattungsmerkmale
      import_strategy: DataCycleCore::Generic::Feratel::ImportFacilitiesCount
    holiday_themes:
      sorting: 16
      source_type: holiday_themes
      tree_label: Feratel - Urlaubsthemen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
    infrastructure_types:
      sorting: 17
      source_type: infrastructure_types
      tree_label: Feratel - Infrastrukturtypen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Type'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: 'Feratel - Infrastrukturtyp - '
    infrastructure_topics:
      sorting: 18
      source_type: infrastructure_topics
      tree_label: Feratel - Infrastrukturklassifizierungen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
    classifications:
      sorting: 19
      source_type: classifications
      tree_label: Feratel - Unterkunftsklassifizierungen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
    stars:
      sorting: 20
      source_type: stars
      tree_label: Feratel - Sterne
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_id_path: 'Id'
      tag_name_path: 'Name.Translation.text'
      external_id_prefix: ''
    product_types:
      sorting: 21
      source_type: accommodations
      tree_label: Feratel - Produktarten
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Services.Service.Products.Product'
      tag_id_path: 'Services.Service.Products.Product.Details.ProductType.text'
      tag_name_path: 'Services.Service.Products.Product.Details.ProductType.text'
      external_id_prefix: 'Feratel - Produktart - '
    accommodation_type:
      sorting: 22
      source_type: accommodations
      tree_label: Feratel - Unterkunftstypen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'Services.Service.Products.Product'
      tag_id_path: 'Services.Service.Products.Product.Details.AccommodationType.text'
      tag_name_path: 'Services.Service.Products.Product.Details.AccommodationType.text'
      external_id_prefix: 'Feratel - Unterkunftstype - '
      locales: [de]
    accommodation_type_additional:
      sorting: 23
      source_type: accommodations
      tree_label: Feratel - Unterkunftstypen
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tag_path: 'AdditionalServices.AdditionalService.Products.Product'
      tag_id_path: 'AdditionalServices.AdditionalService.Products.Product.Details.AccommodationType.text'
      tag_name_path: 'AdditionalServices.AdditionalService.Products.Product.Details.AccommodationType.text'
      external_id_prefix: 'Feratel - Unterkunftstype - '
      locales: [de]
    locations:
      sorting: 24
      source_type: locations
      tree_label: Feratel - Orte
      import_strategy: DataCycleCore::Generic::Feratel::ImportLocations
    infrastructures:
      sorting: 50
      source_type: infrastructure_items
      import_strategy: DataCycleCore::Generic::Feratel::ImportInfrastructure
      transformations:
        image:
          template: Bild
        infrastructure:
          template: POI
    accommodations:
      sorting: 51
      source_type: accommodations
      import_strategy: DataCycleCore::Generic::Feratel::ImportAccommodations
      transformations:
        image:
          template: Bild
        place:
          template: Unterkunft
    events:
      sorting: 52
      source_type: events
      import_strategy: DataCycleCore::Generic::Feratel::ImportEvents
      transformations:
        image:
          template: Bild
        place:
          template: Örtlichkeit
        event:
          template: Event
    delete_infrastructures:
      sorting: 60
      import_strategy: DataCycleCore::Generic::Common::UpdateAttributes
      source_type: infrastructure_items
      source_filter:
        '$or':
          - 'seen_at':
              '$lt': '{{ 3.days.ago.beginning_of_day }}'
      external_key_path: 'Id'
      attributes:
        - key: external_status
          type: classification
          tree_label: Externer Status
          value: Gelöscht
      last_successful_download: 3.days.ago.beginning_of_day
    delete_accommodations:
      sorting: 61
      import_strategy: DataCycleCore::Generic::Common::UpdateAttributes
      source_type: accommodations
      source_filter:
        '$or':
          - 'seen_at':
              '$lt': '{{ 3.days.ago.beginning_of_day }}'
      external_key_path: 'Id'
      attributes:
        - key: external_status
          type: classification
          tree_label: Externer Status
          value: Gelöscht
      last_successful_download: 3.days.ago.beginning_of_day
