---
name: HRS destination-data
credentials:
  host: https://destination-data.oms-ds.com
  end_point: api
  api_key: fafb190b8509c203cc1cfd95d937d101
default_options:
  locales: [de]
config:
  download_config:
    events:
      sorting: 10
      source_type: events
      endpoint: DataCycleCore::Generic::HrsDestinationData::Endpoint
      download_strategy: DataCycleCore::Generic::HrsDestinationData::Download
  import_config:
    classifications:
      sorting: 1
      source_type: events
      import_strategy: DataCycleCore::Generic::HrsDestinationData::ImportClassifications
    events:
      sorting: 10
      source_type: events
      import_strategy: DataCycleCore::Generic::HrsDestinationData::ImportEvents
      transformations:
        event:
