---
name: karriere.at
credentials:
  host: https://www.karriere.at
  end_point: /extern/feed/kaernten_werbung
  fbclid: IwAR30a_6G7CUSZoM0d2X5KItShjgBWvg4C7Bk2wctRpoi3qKXNY6IOnAcZfc
default_options:
  locales: [de]
config:
  download_config:
    jobs:
      sorting: 1
      source_type: jobs
      endpoint: DataCycleCore::Generic::KarriereAt::Endpoint
      download_strategy: DataCycleCore::Generic::KarriereAt::Download
  import_config:
    keywords:
      sorting: 1
      source_type: jobs
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: karriere.at - Keywords
      tag_path: keywords.keyword
      tag_id_path: keywords.keyword.#cdata-section
      tag_name_path: keywords.keyword.#cdata-section
      external_id_prefix: 'karriere.at - Keyword - '
    employment_types:
      sorting: 2
      source_type: jobs
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: karriere.at - Employment Types
      tag_id_path: employmentTypes.employmentType.id
      tag_name_path: employmentTypes.employmentType.#cdata-section
      external_id_prefix: 'karriere.at - Employment Type - '
    job_fields:
      sorting: 3
      source_type: jobs
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: karriere.at - Job Fields
      tag_id_path: jobfields.jobfield.id
      tag_name_path: jobfields.jobfield.#cdata-section
      external_id_prefix: 'karriere.at - Job Field - '
    countries:
      sorting: 4
      source_type: jobs
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: karriere.at - Countries
      tag_path: countries.country
      tag_id_path: countries.country.#cdata-section
      tag_name_path: countries.country.#cdata-section
      external_id_prefix: 'karriere.at - Country - '
    states:
      sorting: 5
      source_type: jobs
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: karriere.at - States
      tag_path: states.state
      tag_id_path: states.state.#cdata-section
      tag_name_path: states.state.#cdata-section
      external_id_prefix: 'karriere.at - State - '
    jobs:
      sorting: 10
      source_type: jobs
      import_strategy: DataCycleCore::Generic::KarriereAt::ImportJob
      transformations:
        organization:
          template: Organization
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Organization
        place:
          template: Örtlichkeit
          default_value:
            data_type:
              tree_label: Inhaltstypen
              value: Örtlichkeit
        job:
          template: JobPosting
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Jobs
