---
name: Local-Text-File
credentials:
  log_file: filename_goes_here
config:
  push_config:
    create:
      strategy: DataCycleCore::Export::TextFile::Create
    update:
      strategy: DataCycleCore::Export::TextFile::Update
    delete:
      strategy: DataCycleCore::Export::TextFile::Delete
  refresh_config:
#      strategy: DataCycleCore::Export::LogFile::Refresh
