---
name: TTG MetaAPI
identifier: metaapi
credentials:
  host: https://api.tourdata.at
  end_point: services/Api
  api_key: 5822663640B7BA30B6E15D9CCAB38CC6
default_options:
  locales: [de]
config:
  download_config:
    accommodation_categories:
      sorting: 1
      source_type: accommodation_categories
      endpoint: DataCycleCore::Generic::Metaapi::Endpoint
      download_strategy: DataCycleCore::Generic::Metaapi::Download
    gastronomy_categories:
      sorting: 2
      source_type: gastronomy_categories
      endpoint: DataCycleCore::Generic::Metaapi::Endpoint
      download_strategy: DataCycleCore::Generic::Metaapi::Download
    poi_categories:
      sorting: 3
      source_type: poi_categories
      endpoint: DataCycleCore::Generic::Metaapi::Endpoint
      download_strategy: DataCycleCore::Generic::Metaapi::Download
    tour_categories:
      sorting: 4
      source_type: tour_categories
      endpoint: DataCycleCore::Generic::Metaapi::Endpoint
      download_strategy: DataCycleCore::Generic::Metaapi::Download
    event_categories:
      sorting: 5
      source_type: event_categories
      endpoint: DataCycleCore::Generic::Metaapi::Endpoint
      download_strategy: DataCycleCore::Generic::Metaapi::Download
  import_config:
    accommodation_categories:
      sorting: 1
      source_type: accommodation_categories
      import_strategy: DataCycleCore::Generic::Metaapi::ImportCategories
      tree_label: 'TTG MetaAPI - Unterkunft-Kategorien'
      external_id_prefix: 'TTG MetaAPI - Unterkunft-Kategorie - '
    gastronomy_categories:
      sorting: 2
      source_type: gastronomy_categories
      import_strategy: DataCycleCore::Generic::Metaapi::ImportCategories
      tree_label: 'TTG MetaAPI - Gastronomie-Kategorien'
      external_id_prefix: 'TTG MetaAPI - Gastronomie-Kategorie - '
    poi_categories:
      sorting: 3
      source_type: poi_categories
      import_strategy: DataCycleCore::Generic::Metaapi::ImportCategories
      tree_label: 'TTG MetaAPI - POI-Kategorien'
      external_id_prefix: 'TTG MetaAPI - POI-Kategorie - '
    tour_categories:
      sorting: 4
      source_type: tour_categories
      import_strategy: DataCycleCore::Generic::Metaapi::ImportCategories
      tree_label: 'TTG MetaAPI - Tour-Kategorien'
      external_id_prefix: 'TTG MetaAPI - Tour-Kategorie - '
    event_categories:
      sorting: 5
      source_type: event_categories
      import_strategy: DataCycleCore::Generic::Metaapi::ImportCategories
      tree_label: 'TTG MetaAPI - Veranstaltung-Kategorien'
      external_id_prefix: 'TTG MetaAPI - Veranstaltung-Kategorie - '
