---
name: OpenStreetMap
credentials:
  storage_type: local
  # directory: ./test/fixtures/files/shp
  directory: /home/pixelpoint/geodata-admin-boundaries/administrative_boundaries/OSM/shp/3035
  delete: false
config:
  download_config:
    # could be used to download assets to local storage
    shp:
      sorting: 1
      source_type: shp
      endpoint:  DataCycleCore::Generic::GeoShape::Endpoint
      download_strategy:  DataCycleCore::Generic::GeoShape::Download
  import_config:
    shp:
      sorting: 1
      source_type: shp
      srid: 3035
      geometry_type: DataCycleCore::ClassificationPolygon
      db_table: classification_polygons
      import_strategy: DataCycleCore::Generic::GeoShape::Import
      tree_label: Administrative Einheiten
