---
name: OutdoorActive
credentials:
  xml:
    source: 'dataCycle'
    owner: 'dataCycleKW'
  host: 'http://web:3000'
  key: 'datacycle'
config:
  push_config:
    endpoint: DataCycleCore::Export::OutdoorActive::Endpoint
    create:
      strategy: DataCycleCore::Export::OutdoorActive::Create
    update:
      strategy: DataCycleCore::Export::OutdoorActive::Update
    delete:
      strategy: DataCycleCore::Export::OutdoorActive::Delete
