---
name: OutdoorActive
credentials:
  request_url: 'http://localhost:3010'
  source: 'dataCycle'
  owner: 'dataCycleKW'
config:
  push_config:
    endpoint: DataCycleCore::Export::OutdoorActive::Endpoint
    create:
      strategy: DataCycleCore::Export::OutdoorActive::Create
    update:
      strategy: DataCycleCore::Export::OutdoorActive::Update
    delete:
      strategy: DataCycleCore::Export::OutdoorActive::Delete
