---
name: OutdoorActive
credentials:
  xml:
    source: 'datacycle-kaernten'
#    owner: 'woerthersee'
  host: 'http://web:3000'
  key: 'datacycle-kaernten'
  external_source: 'OutdoorActive Kärnten'
config:
  push_config:
    endpoint: DataCycleCore::Export::OutdoorActive::Endpoint
    update:
      strategy: DataCycleCore::Export::OutdoorActive::Update
    delete:
      strategy: DataCycleCore::Export::OutdoorActive::Delete
  refresh_config:
    endpoint: DataCycleCore::Export::OutdoorActive::Endpoint
    strategy: DataCycleCore::Export::OutdoorActive::JobStatus

