---
name: Pimcore
identifier: pimcore
credentials:
  host: https://www.montafon.at
  url_part: webservice/imx
  end_point: infrastructure
  apikey: 6b46d5f1240824f1a27b6aaa3641e03d96694789f5700d149dae2aa144ea150d
  endpoint_bergerlebnis: json/bergerlebnis
  endpoint_event: json/event
  endpoint_eventreihe: json/eventreihe
default_options:
  locales: [de, en]
config:
  download_config:
    infrastructures:
      sorting: 1
      source_type: infrastructures
      endpoint: DataCycleCore::Generic::Pimcore::Endpoint
      download_strategy: DataCycleCore::Generic::Pimcore::Download
    bergerlebnis:
      sorting: 2
      source_type: bergerlebnis
      endpoint: DataCycleCore::Generic::Pimcore::Endpoint
      download_strategy: DataCycleCore::Generic::Pimcore::DownloadEvent
    event:
      sorting: 3
      source_type: event
      read_type: bergerlebnis
      endpoint: DataCycleCore::Generic::Pimcore::Endpoint
      download_strategy: DataCycleCore::Generic::Pimcore::DownloadEvent
    eventreihe:
      sorting: 4
      source_type: eventreihe
      endpoint: DataCycleCore::Generic::Pimcore::Endpoint
      download_strategy: DataCycleCore::Generic::Pimcore::DownloadEvent
  import_config:
    categories:
      sorting: 1
      source_type: infrastructures
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: 'Pimcore - Categories'
      tag_id_path: 'categories.id'
      tag_name_path: 'categories.name'
      external_id_prefix: 'Pimcore - Category - '
    city:
      sorting: 2
      source_type: infrastructures
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: 'Pimcore - Cities'
      tag_id_path: 'city.id'
      tag_name_path: 'city.name'
      external_id_prefix: 'Pimcore - City - '
    images:
      sorting: 5
      source_type: infrastructures
      import_strategy: DataCycleCore::Generic::Pimcore::ImportImages
      transformations:
        image:
          template: Bild
          content_url_prefix: 'https://www.montafon.at'
    infrastructures:
      sorting: 20
      source_type: infrastructures
      import_strategy: DataCycleCore::Generic::Pimcore::ImportInfrastructure
      transformations:
        image:
          template: Bild
        infrastructure:
          template: POI
    event_categories:
      sorting: 30
      source_type: event
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: 'Pimcore - Event-Categories'
      tag_id_path: 'categories'
      tag_name_path: 'categories'
      external_id_prefix: 'Pimcore - Event-Category - '
    event_locations:
      sorting: 31
      source_type: event
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: 'Pimcore - Locations'
      tag_id_path: 'locations'
      tag_name_path: 'locations'
      external_id_prefix: 'Pimcore - Location - '
    event_images:
      sorting: 40
      source_type: event
      import_strategy: DataCycleCore::Generic::Pimcore::ImportEventImages
      transformations:
        image:
          template: Bild
    events:
      sorting: 41
      source_type: event
      import_strategy: DataCycleCore::Generic::Pimcore::ImportEvent
      transformations:
        image:
          template: Bild
        event:
          template: Event
