---
name: reisen-fuer-alle.de
credentials:
  host: https://partner-api.reisen-fuer-alle.de
  end_point: output/api
  user: zlattinger@pixelpoint.at
  token: tPE8CmVGDgr6BfJ7SnWb6Zz3+iUz
  external_source_feratel: Feratel Rheinland-Pfalz
  external_source_outdoor_active: Outdooractive Rheinland-Pfalz
default_options:
  locales: [de]
config:
  download_config:
    ratings:
      sorting: 1
      source_type: ratings
      endpoint: DataCycleCore::Generic::ReisenFuerAlle::Endpoint
      download_strategy: DataCycleCore::Generic::ReisenFuerAlle::Download
  import_config:
    licence_owner:
      sorting: 1
      source_type: ratings
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: 'reisen-fuer-alle.de - Lizenznehmer'
      tag_id_path: 'licence_owner'
      tag_name_path: 'licence_owner'
      external_id_prefix: 'reisen-fuer-alle.de - Lizenznehmer - '
    certificate_deaf:
      sorting: 10
      source_type: ratings
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::ImportTags
      tree_label: 'reisen-fuer-alle.de - Zertifikat - Gehörlos'
      tag_id_path: 'certificate_data.deaf.level'
      tag_name_path: 'certificate_data.deaf.level'
      tag_uri_path: 'certificate_data.deaf.icon_url'
      external_id_prefix: 'reisen-fuer-alle.de - Zertifikat - Gehörlos - '
    certificate_mental:
      sorting: 11
      source_type: ratings
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::ImportTags
      tree_label: 'reisen-fuer-alle.de - Zertifikat - Kognitiv'
      tag_id_path: 'certificate_data.mental.level'
      tag_name_path: 'certificate_data.mental.level'
      tag_uri_path: 'certificate_data.mental.icon_url'
      external_id_prefix: 'reisen-fuer-alle.de - Zertifikat - Kognitiv - '
    certificate_partially_deaf:
      sorting: 12
      source_type: ratings
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::ImportTags
      tree_label: 'reisen-fuer-alle.de - Zertifikat - Hörbehinderung'
      tag_id_path: 'certificate_data.partially_deaf.level'
      tag_name_path: 'certificate_data.partially_deaf.level'
      tag_uri_path: 'certificate_data.partially_deaf.icon_url'
      external_id_prefix: 'reisen-fuer-alle.de - Zertifikat - Hörbehinderung - '
    certificate_partially_visual:
      sorting: 13
      source_type: ratings
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::ImportTags
      tree_label: 'reisen-fuer-alle.de - Zertifikat - Sehbehinderung'
      tag_id_path: 'certificate_data.partially_visual.level'
      tag_name_path: 'certificate_data.partially_visual.level'
      tag_uri_path: 'certificate_data.partially_visual.icon_url'
      external_id_prefix: 'reisen-fuer-alle.de - Zertifikat - Sehbehinderung - '
    certificate_visual:
      sorting: 14
      source_type: ratings
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::ImportTags
      tree_label: 'reisen-fuer-alle.de - Zertifikat - Blind'
      tag_id_path: 'certificate_data.visual.level'
      tag_name_path: 'certificate_data.visual.level'
      tag_uri_path: 'certificate_data.visual.icon_url'
      external_id_prefix: 'reisen-fuer-alle.de - Zertifikat - Blind - '
    certificate_walking:
      sorting: 15
      source_type: ratings
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::ImportTags
      tree_label: 'reisen-fuer-alle.de - Zertifikat - Gehbehinderung'
      tag_id_path: 'certificate_data.walking.level'
      tag_name_path: 'certificate_data.walking.level'
      tag_uri_path: 'certificate_data.walking.icon_url'
      external_id_prefix: 'reisen-fuer-alle.de - Zertifikat - Gehbehinderung - '
    certificate_wheelchair:
      sorting: 16
      source_type: ratings
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::ImportTags
      tree_label: 'reisen-fuer-alle.de - Zertifikat - Rollstuhl'
      tag_id_path: 'certificate_data.wheelchair.level'
      tag_name_path: 'certificate_data.wheelchair.level'
      tag_uri_path: 'certificate_data.wheelchair.icon_url'
      external_id_prefix: 'reisen-fuer-alle.de - Zertifikat - Rollstuhl - '
    ratings:
      sorting: 20
      source_type: ratings
      source_filter:
        'dump.de.licence_owner': 'Rheinland-Pfalz Tourismus GmbH'
      import_strategy: DataCycleCore::Generic::ReisenFuerAlle::Import
      # transformations:
      #   place:
      #     template: Örtlichkeit
      #   image:
      #     template: Bild
      #   organizer:
      #     template: Organization
