---
name: V-Ticket
credentials:
  action: ACTION
  end_point: ENDPOINT
  host: HOST
  token: TOKEN
default_options:
  locales: [de]
config:
  download_config:
    events:
      sorting: 2
      source_type: events
      endpoint: DataCycleCore::Generic::VTicket::Endpoint
      download_strategy: DataCycleCore::Generic::VTicket::Download
  import_config:
    tags:
      sorting: 1
      source_type: events
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: VTicket - Tags
      tag_id_path: 'tags'
      tag_name_path: 'tags'
      external_id_prefix: 'VTicket - Tags - '
    categories:
      sorting: 1
      source_type: events
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: VTicket - Categories
      tag_id_path: 'categories'
      tag_name_path: 'categories'
      external_id_prefix: 'VTicket - Categories - '
    events:
      sorting: 3
      source_type: events
      import_strategy: DataCycleCore::Generic::VTicket::ImportEvents
      transformations:
        image:
          template: Bild
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Bild
        place:
          template: Örtlichkeit
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Örtlichkeit
        event:
          template: Event
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Veranstaltung
          embedded:
            sub_event:
              template: SubEvent
              default_values:
                data_type:
                  tree_label: Inhaltstypen
                  value: Veranstaltungstermin
