---
name: V-Ticket
credentials:
  action: /events
  end_point: /api/v2
  host: https://eventserver.v-ticket.at
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjQ4YjJhYmZhNzA1OTE1ODY4MjRiN2FhZDZhODI1MWM0OTlhNGMyZThhZGI4YTcyNGEzYTFiNmIxYTIwZWZiMGFkZjg4ODk4MDdkZDRjZGFiIn0.eyJhdWQiOiIxIiwianRpIjoiNDhiMmFiZmE3MDU5MTU4NjgyNGI3YWFkNmE4MjUxYzQ5OWE0YzJlOGFkYjhhNzI0YTNhMWI2YjFhMjBlZmIwYWRmODg4OTgwN2RkNGNkYWIiLCJpYXQiOjE1Nzg0NjY4NTUsIm5iZiI6MTU3ODQ2Njg1NSwiZXhwIjoxNjEwMDg5MjU1LCJzdWIiOiIxMCIsInNjb3BlcyI6W119.LtMc6gDKNawxjD9VqAn4AFIPh2yx1OzrGblkbWUM_I0bm-whvkZ9un1H2rWGtcUGJjxJopYCQeV24YswYQiqgRvssqy4ZdZIzsIaWZfiqiCdKTPxRm6yrIk48gFDpeOnc3-dWbgJOuTKrsTdWDNTIkQEOd3cNX3tUYQ3a0XptzWCeu3h2BjvUuHTyNuqOWjPg3MC0kUrAdWosmhs86Qh5ws0-UFk0BPs-Kwonil1Qh6l30VR9w84FQZmzrAexhhkeOqj0Ok-13DBNYTDT0027Y3VdItd_WRYcgySHIz_e6PBCj_iazYidfViYXB_TgQL5S4hDPZgClJ6KwAbghwOTPCdaZCKpAYlrhXEX_a5hkT-ioPmWUzx62VAfOFJLd7tU7aTINs63wcFknAJbxvRCxWSd4zePY4kLi36AFejT8Za9Jy9bqUIZTOmEa5mgdR-yqRlBWv8R1DPAuL4m6TpCRNudBHIVFqYYHYBYTwSx9g8wqyj2b5ASj92BeNezU8AGGGQcydCmy2gXZvKc_cgtGF3nKDmjfZ07Yq4GpI7Jeedv0uuaE5TyXa7WTe2g2BIEHFfuHEndG0hCvyyWgbWEFkr_6lrHDQURkUSCr-R5YewgmBEfWChTyuPN6vTunO1oxqvnDhWcqipiXiFem5PLQxcLGLrFWGndU1Nxo4RMF0'
default_options:
  locales: [de]
config:
  download_config:
    events:
      sorting: 2
      source_type: events
      endpoint: DataCycleCore::Generic::VTicket::Endpoint
      download_strategy: DataCycleCore::Generic::VTicket::Download
  import_config:
    tags:
      sorting: 1
      source_type: events
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: VTicket - Tags
      tag_id_path: 'tags'
      tag_name_path: 'tags'
      external_id_prefix: 'VTicket - Tags - '
    categories:
      sorting: 1
      source_type: events
      import_strategy: DataCycleCore::Generic::Common::ImportTags
      tree_label: VTicket - Categories
      tag_id_path: 'categories'
      tag_name_path: 'categories'
      external_id_prefix: 'VTicket - Categories - '
    events:
      sorting: 3
      source_type: events
      import_strategy: DataCycleCore::Generic::VTicket::ImportEvents
      transformations:
        image:
          template: Bild
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Bild
        place:
          template: Örtlichkeit
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Örtlichkeit
        event:
          template: Event
          default_values:
            data_type:
              tree_label: Inhaltstypen
              value: Veranstaltung
          embedded:
            sub_event:
              template: SubEvent
              default_values:
                data_type:
                  tree_label: Inhaltstypen
                  value: Veranstaltungstermin
