---
- :data:
    :name: contact_info
    :type: mixin
    # schema.org: APIv2 Breaking Change (transformations)
    :properties:
      :contact_info:
        :label: Kontakt
        :type: object
        :storage_location: translated_value
        :api:
          :transformation:
            :method: merge_object
            :name: address
        :properties:
          :telephone:
            :label: Telefonnummer
            :type: string
            :storage_location: translated_value
          :fax_number:
            :label: Fax
            :type: string
            :storage_location: translated_value
          :email:
            :label: E-Mail
            :type: string
            :storage_location: translated_value
          :url:
            :label: Web
            :type: string
            :storage_location: translated_value
