---
- :data:
    :name: copyright_attributes
    :type: mixin
    :properties:

      # used in importer
      # oewein => show/edit disabled and api disabled
      # @todo: disable
      :license:
        :label: Copyright / Lizenz
        :type: string
        :storage_location: value
        :search: false
        :external: true
        :api:
          :disabled: true
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true

      # legacy API Attribute
      :legacy_license:
        :label: LegacyLicense
        :type: virtual
        :virtual:
          :type: string
          :module: Utility::Virtual::Common
          :method: take_first
          :parameters:
            :0: copyright_notice_override
            :1: copyright_notice_computed
        :api:
          :disabled: false
          :name: 'cc:license'
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true
      
      # used in importer, serializer => Eyebase, wikidata
      # oew => computed! (like computed_attribution_name), api => :name: 'cc:attributionName' => use virtual(copyright_notice)
      # vcloud => computed! (like computed_attribution_name), api => :name: 'cc:attributionName'
      # vcloud_bodensee => computed! (like computed_attribution_name), api => :name: 'cc:attributionName'
      # oewein => computed! (like computed_attribution_name), api => disabled
      # @todo: disable
      :attribution_name:
        :label: Namensnennung
        :type: string
        :storage_location: value
        :search: false
        :external: true
        :api:
          :disabled: true
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true

      # legacy API Attribute
      :legacy_attribution_name:
        :label: LegacyAttributionName
        :type: virtual
        :virtual:
          :type: string
          :module: Utility::Virtual::Common
          :method: take_first
          :parameters:
            :0: copyright_notice_override
            :1: copyright_notice_computed
        :api:
          :disabled: false
          :name: 'cc:attributionName'
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true


      # used in importer  => obsolete => delete
      # => destinationOne + wikiData
      # importer must use => url 
      # @todo: disable
      :attribution_url:
        :label: Namensnennung - Url
        :type: string
        :storage_location: value
        :search: true
        :external: true
        :api:
          :v4:
            :name: 'cc:attributionUrl'
      
      # FINAL
      :use_guidelines:
        :label: Verwendungsrichtlinie
        :type: string
        :storage_location: translated_value
        :search: true
        :external: true
        :api:
          :v4:
            :name: 'cc:useGuidelines'

      # latest validate: API output
      # used in importer
      # api: license => classification.url
      # oew => used as license string
      # vcloud => used as license string
      # vcloud - bodensee => used as license string
      # brandenburg - bodensee => used as license string
      # cc:license + license
      :license_classification:
        :label: Lizenzen
        :type: classification
        :tree_label: Lizenzen
        :global: true
        :ui:
          :show:
            :content_area: header
        :api:
          :disabled: true
          :v4:
            :name: 'cc:license'
            :disabled: false
            :partial: string

      # FINAL
      # => copyright_notice_override
      # :explicit_copyright_notice:
      #   :label: raw_imported_copyright
      #   :type: string
      #   :storage_location: translated_value
      #   :api:
      #     :disabled: true
      #   :xml:
      #     :disabled: true
      #   :ui:
      #     :edit:
      #       :disabled: true
      #     :show:
      #       :disabled: true
      
      # latest test virtual in serializer
      # used in license serializer
      # vcloud: overwrite compute method
      # @todo: disable
      # :computed_attribution_name:
      #   :label: hidden attribution name
      #   :storage_location: translated_value
      #   :type: computed
      #   :search: true
      #   :external: false
      #   :compute:
      #     :type: string
      #     :module: Utility::Compute::String
      #     :method: attribution_name
      #     :parameters:
      #       :0: copyright_holder
      #       :1: author
      #   :api:
      #     :disabled: true
      #   :ui:
      #     :show:
      #       :disabled: true

      # new
      :copyright_notice_computed:
        :label: Urheberrechtsvermerk (automatisch)
        :storage_location: value
        :type: computed
        :compute:
          :type: string
          :module: Utility::Compute::Copyright
          :method: copyright_notice
          :parameters:
            :0: license_classification
            :1: author
            :2: copyright_holder
            :3: copyright_year
        :search: true
        :api:
          :disabled: true
        :ui:
          :edit:
            :disabled: true
      
      # new
      :copyright_notice_override:
        :label: Urheberrechtsvermerk (manuell)
        :storage_location: value
        :type: string
        :search: true
        :api:
          :disabled: true
        :ui:
          :edit:
            :disabled: false
      
      # new
      :copyright_notice:
        :label: Urheberrechtsvermerk
        :type: virtual
        :virtual:
          :type: string
          :module: Utility::Virtual::Common
          :method: take_first
          :parameters:
            :0: copyright_notice_override
            :1: copyright_notice_computed
        :api:
          :disabled: false
        :ui:
          :edit:
            :disabled: true
