---
- :data:
    :name: geo_shape
    :type: mixin
    :properties:
      :tour:
        :label: Route
        :type: geographic
        :storage_location: value
        :ui:
          :edit:
            :disabled: true
        :api:
          :minimal: true
          :disabled: false
          :v4:
            :name: line
            :transformation:
              :method: nest
              :name: geo
              :type: GeoShape