---
- :data:
    :name: postal_address
    :type: mixin
    :properties:
      :address:
        :label: Adresse
        :type: object
        :storage_location: value
        :api:
          :type: PostalAddress
        :properties:
          :street_address:
            :label: Straße
            :type: string
            :storage_location: value
          :postal_code:
            :label: PLZ
            :type: string
            :storage_location: value
          :address_locality:
            :label: Ort
            :type: string
            :storage_location: value
          :address_country:
            :label: Land
            :type: string
            :storage_location: value
      :country_code:
        :label: Ländercode
        :type: classification
        :tree_label: Ländercodes
        :ui:
          :show:
            :content_area: header
        :api:
          :partial: country_code
