- :data:
    :name: Zertifizierung
    :type: object
    :schema_type: Intangible
    :content_type: entity
    :api:
      :type: 'dc:certification'
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Zertifiziert
        :type: string
        :storage_location: column
        :search: true
      :linked_data:
        :name: linked_data
        :type: mixin
      :certification_period:
        :label: Zertifizierungszeitraum
        :type: object
        :storage_location: value
        :validations:
          :daterange:
            :from: certified_from
            :to: certified_to
        :ui:
          :edit:
            :type: daterange
        :properties:
          :certified_from:
            :label: Zertifizierung
            :type: datetime
            :storage_location: value
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: date
                :options:
                  :data-validate: daterange
                  :placeholder: tt.mm.jjjj
          :certified_to:
            :label: bis
            :type: datetime
            :storage_location: value
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: date
                :options:
                  :data-validate: daterange
                  :placeholder: tt.mm.jjjj
      :certification_type:
        :label: Zertifizierungstyp
        :type: object
        :storage_location: translated_value
        :properties:
          :designation:
            :label: Bezeichnung
            :type: string
            :storage_location: translated_value
            :search: true
          :key:
            :label: Wert
            :type: string
            :storage_location: translated_value
            :search: true
          :icon:
            :label: Symbol
            :type: string
            :storage_location: translated_value
      :public_pdf:
        :label: Öffentliche Dokumente
        :type: object
        :storage_location: translated_value
        :properties:
          :allergic:
            :label: Allergien
            :type: string
            :storage_location: translated_value
          :deaf:
            :label: Hören
            :type: string
            :storage_location: translated_value
          :generations:
            :label: Generationen
            :type: string
            :storage_location: translated_value
          :mental:
            :label: Kognitiv
            :type: string
            :storage_location: translated_value
          :visual:
            :label: Sehen
            :type: string
            :storage_location: translated_value
          :walking:
            :label: Gehen
            :type: string
            :storage_location: translated_value
          :wheelchair:
            :label: Rollstuhl
            :type: string
            :storage_location: translated_value
      :short_report:
        :label: Kurzbericht
        :type: object
        :storage_location: translated_value
        :properties:
          :deaf:
            :label: Hören
            :type: string
            :storage_location: translated_value
            :search: true
            :ui:
              :edit:
                :type: text_editor
                :options:
                  :data-size: full
          :mental:
            :label: Kognitiv
            :type: string
            :storage_location: translated_value
            :search: true
            :ui:
              :edit:
                :type: text_editor
                :options:
                  :data-size: full
          :visual:
            :label: Sehen
            :type: string
            :storage_location: translated_value
            :search: true
            :ui:
              :edit:
                :type: text_editor
                :options:
                  :data-size: full
          :walking:
            :label: Gehen/Rollstuhl
            :type: string
            :storage_location: translated_value
            :search: true
            :ui:
              :edit:
                :type: text_editor
                :options:
                  :data-size: full
      :licence_owner:
        :label: Lizenznehmer
        :type: classification
        :tree_label: reisen-fuer-alle.de - Lizenznehmer
        :global: true
        :ui:
          :show:
            :content_area: header
      :certification_deaf:
        :label: Zertifikat Gehörlos
        :type: classification
        :tree_label: reisen-fuer-alle.de - Zertifikat - Gehörlos
        :global: true
        :ui:
          :show:
            :content_area: header
      :certification_mental:
        :label: Zertifikat Kognitiv
        :type: classification
        :tree_label: reisen-fuer-alle.de - Zertifikat - Kognitiv
        :global: true
        :ui:
          :show:
            :content_area: header
      :certification_partially_deaf:
        :label: Zertifikat Hörbehinderung
        :type: classification
        :tree_label: reisen-fuer-alle.de - Zertifikat - Hörbehinderung
        :global: true
        :ui:
          :show:
            :content_area: header
      :certification_partially_visual:
        :label: Zertifikat Sehbehinderung
        :type: classification
        :tree_label: reisen-fuer-alle.de - Zertifikat - Sehbehinderung
        :global: true
        :ui:
          :show:
            :content_area: header
      :certification_visual:
        :label: Zertifikat Blind
        :type: classification
        :tree_label: reisen-fuer-alle.de - Zertifikat - Blind
        :global: true
        :ui:
          :show:
            :content_area: header
      :certification_walking:
        :label: Zertifikat Gehbehinderung
        :type: classification
        :tree_label: reisen-fuer-alle.de - Zertifikat - Gehbehinderung
        :global: true
        :ui:
          :show:
            :content_area: header
      :certification_wheelchair:
        :label: Zertifikat Rollstuhl
        :type: classification
        :tree_label: reisen-fuer-alle.de - Zertifikat - Rollstuhl
        :global: true
        :ui:
          :show:
            :content_area: header
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: Zertifizierung
      :meta_data:
        :type: mixin
        :name: meta_data
