---
- :data:
    :name: feratel_classifications
    :type: mixin
    :properties:
      :feratel_owners:
        :label: Feratel - Inhaber
        :type: classification
        :tree_label: Feratel - Inhaber
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :feratel_status:
        :label: Feratel - Status
        :type: classification
        :tree_label: Feratel - Status
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :feratel_shop_item_groups:
        :label: Feratel - ShopItemGroups
        :type: classification
        :tree_label: Feratel - ShopItemGroups
        :external: true
        :not_translated: true
        :ui:
          :show:
            :content_area: header
      :holiday_themes:
        :label: Feratel - Urlaubsthemen
        :type: classification
        :tree_label: Feratel - Urlaubsthemen
        :external: true
        :ui:
          :show:
            :content_area: header
      :language_variations:
        :label: Sprachvarianten
        :type: classification
        :tree_label: Feratel - Sprachvarianten
        :external: true
        :ui:
          :show:
            :content_area: header
