---
- :data:
    :name: meta_data_mixin
    :type: mixin
    :properties:
      :creator:
        :label: Ersteller
        :type: embeddedLink
        :type_name: users
        :storage_type: string
        :storage_location: metadata
      :date_created:
        :label: Erstellungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time
      :date_modified:
        :label: Änderungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time