---
- :data:
    :name: additional_image_properties
    :type: mixin
    :properties:
      :image_variants:
        :label: Bild-Varianten
        :type: embedded
        :template_name: ImageVariant
        :translated: true
