- Inhaltstypen | filter, classification_administration:
    - $$Asset:
        - $$Webcam
    - $$Ort:
        - $$Skigebiet
        - $$Zusatzangebot
        - $$Wetterstation Feratel
        - $$Wetterprognose
