---
- :data:
    :name: Organization
    :type: object
    :content_type: entity
    :permissions:
      :read_write: true
    :boost: 1.0
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :legal_name:
        :label: Firmenname
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :options:
            :data-validate: text
      :contact_info:
        :type: mixin
        :name: contact_info
      :postal_address:
        :type: mixin
        :name: postal_address
      :description:
        :label: Text
        :type: string
        :storage_type: text
        :storage_location: column
        :search: true
        :editor:
          :type: quillEditor
          :options:
            :data-size: full
      :image:
        :label: Bild
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: array
        :storage_location: metadata
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Organisation"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties