---
- :data:
    :name: Organization
    :type: object
    :content_type: entity
    :permissions:
      :read_write: true
    :boost: 1.0
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :name:
        :label: Name
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :sorting: 1
          :options:
            :data-validate: text
      :legal_name:
        :label: Firmenname
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :sorting: 2
          :options:
            :data-validate: text
      :telephone:
        :label: Telefonnummer
        :type: string
        :storage_type: string
        :storage_location: metadata
        :editor:
          :type: input
          :sorting: 4
      :fax_number:
        :label: Fax
        :type: string
        :storage_type: string
        :storage_location: metadata
        :editor:
          :type: input
          :sorting: 5
      :email:
        :label: E-Mail
        :type: string
        :storage_type: string
        :storage_location: metadata
        :editor:
          :type: input
          :sorting: 6
      :address:
        :label: Adresse
        :type: object
        :storage_location: metadata
        :editor:
          :sorting: 8
          :options:
            :class: detail_object
        :properties:
          :address_locality:
            :label: Ort
            :type: string
            :storage_type: string
            :storage_location: metadata
            :editor:
              :type: input
              :sorting: 1
          :street_address:
            :label: Straße
            :type: string
            :storage_type: string
            :storage_location: metadata
            :editor:
              :type: input
              :sorting: 2
          :postal_code:
            :label: PLZ
            :type: string
            :storage_type: string
            :storage_location: metadata
            :editor:
              :type: input
              :sorting: 3
      :url:
        :label: Web
        :type: string
        :storage_type: string
        :storage_location: metadata
        :editor:
          :type: input
          :sorting: 9
      :description:
        :label: Text
        :type: string
        :storage_type: text
        :storage_location: content
        :search: true
        :editor:
          :type: quillEditor
          :sorting: 10
          :options:
            :data-size: full
      :image:
        :label: Bild
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: array
        :storage_location: metadata
        :editor:
          :sorting: 11
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Person"
      :creator:
        :label: Ersteller
        :type: embeddedLink
        :type_name: users
        :storage_type: string
        :storage_location: metadata
      :date_created:
        :label: Erstellungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time
      :date_modified:
        :label: Änderungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time