default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  # push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  push_api_key: "ffb2c81e-7d56-4706-8f4c-d7a3e47240f9"

  # Your app's name
  name: "core.datacycle.at"

  active: false
