development:
  adapter: redis
  url: <%= "redis://#{Rails.application.secrets.redis_server}:#{Rails.application.secrets.redis_port}/#{Rails.application.secrets.redis_cache_database}" %>
  channel_prefix: <%= Rails.application.secrets.redis_cache_namespace %>

test:
  adapter: async

staging:
  adapter: redis
  url: <%= "redis://#{Rails.application.secrets.redis_server}:#{Rails.application.secrets.redis_port}/#{Rails.application.secrets.redis_cache_database}" %>
  channel_prefix: <%= Rails.application.secrets.redis_cache_namespace %>

production:
  adapter: redis
  url: <%= "redis://#{Rails.application.secrets.redis_server}:#{Rails.application.secrets.redis_port}/#{Rails.application.secrets.redis_cache_database}" %>
  channel_prefix: <%= Rails.application.secrets.redis_cache_namespace %>
