- :data:
    :name: AmenityFeature
    :type: object
    :schema_type: Intangible
    :content_type: embedded
    :api:
      :type: PropertyValue
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Titel
        :type: string
        :storage_location: column
      :value:
        :label: value
        :type: number
        :storage_location: value
