---
- :data:
    :name: dataCycleEventOverlay
    :type: object
    :schema_type: Event
    :content_type: embedded
    :features:
      :translatable:
        :allowed: true
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Titel
        :type: string
        :storage_location: column
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :image:
        :label: Bilder
        :type: linked
        :template_name: Bild
      :url:
        :label: URL
        :type: string
        :storage_location: translated_value
        :validations:
          :format: url
        :api:
          :name: sameAs
      :content_location:
        :label: Veranstaltungsort
        :type: linked
        :template_name: Örtlichkeit
        :validations:
          :max: 1
        :api:
          :name: location
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Overlay"
