- Inhaltstypen | filter:
    - $$Ort:
        - $$Route
        - $$Gesamtroute
    - $$Text:
        - $$Radroutenbeschreibung

- Gemeinde | all:
    - Villach Stadt
    - Villach Land

- Wegpunkttyp | all:
    - Start
    - Ziel
