---
- :data:
    :name: Publikations-Plan
    :type: object
    :content_type: embedded
    :boost: 1.0
    :properties:
      :id:
        :label: id
        :type: key
      :publish_at:
        :label: Publikationsdatum
        :type: datetime
        :storage_location: value
        :validations:
          :format: date_time
          :min: 1
        :ui:
          :edit:
            :type: date
            :options:
              :data-validate: daterange
              :placeholder: tt.mm.jjjj
      :output_channel:
        :tree_label: Themenbereiche
        :label: Ausgabekanäle
        :type: classification
        :tree_label: Ausgabekanäle
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Publikations-Plan"
      :meta_data:
        :type: mixin
        :name: meta_data
