---
- :data:
    :name: Quiz
    :type: object
    :content_type: entity
    :releasable: true
    :permissions:
      :read_write: true
    :boost: 100.0
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :headline:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :sorting: 1
          :options:
            :data-validate: text
      # mixin: validity_period
      :validity_period:
        :label: Gültigkeitszeitraum
        :type: object
        :storage_location: metadata
        :validations:
          :daterange:
            :from: valid_from
            :to: valid_until
        :editor:
          :sorting: 3
          :options:
            :class: daterange
        :properties:
          :valid_from:
            :label: Gültigkeit
            :type: string
            :storage_type: string
            :storage_location: metadata
            :validations:
              :format: date_time
            :editor:
              :type: date
              :options:
                :data-type: datepicker
                :data-validate: daterange
                :placeholder: tt.mm.jjjj
          :valid_until:
            :label: bis
            :type: string
            :storage_type: string
            :storage_location: metadata
            :validations:
              :format: date_time
            :editor:
              :type: date
              :options:
                :data-type: datepicker
                :data-validate: daterange
                :placeholder: tt.mm.jjjj
      :alternative_headline:
        :label: Subüberschrift
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :editor:
          :type: input
          :sorting: 4
      :description:
        :label: Teasertext
        :type: string
        :storage_type: text
        :storage_location: column
        :search: true
        :editor:
          :type: quillEditor
          :sorting: 5
          :options:
            :data-size: full
      :question:
        :label: Frage
        :type: object
        :storage_location: creative_works
        :delete: true
        :name: Frage
        :editor:
          :type: embeddedObject
          :sorting: 6
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Quiz"
      # mixin: content_classifications
      :topic:
        :label: Themenbereiche
        :type: classificationTreeLabel
        :type_name: Themenbereiche
        :storage_location: classification_relation
        :editor:
          :type: classificationSelector
          :sorting: 11
      :output_channel:
        :label: Ausgabekanal
        :type: classificationTreeLabel
        :type_name: Ausgabekanäle
        :storage_location: classification_relation
        :editor:
          :type: classificationSelector
          :sorting: 12
      # mixin: meta_data
      :creator:
        :label: Ersteller
        :type: embeddedLink
        :type_name: users
        :storage_type: string
        :storage_location: metadata
      :date_created:
        :label: Erstellungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time
      :date_modified:
        :label: Änderungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time


- :data:
    :name: Frage
    :type: object
    :content_type: embedded
    :permissions:
      :read_write: true
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :headline:
        :label: Frage
        :type: string
        :storage_type: string
        :storage_location: column
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :sorting: 1
          :options:
            :data-validate: text
      :text:
        :label: Hinweis
        :type: string
        :storage_type: text
        :storage_location: content
        :editor:
          :type: quillEditor
          :sorting: 4
          :options:
            :data-size: basic
      :image:
        :label: Bild
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: array
        :storage_location: metadata
        :validations:
          :max: 1
        :editor:
          :sorting: 5
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :accepted_answer:
        :label: Richtige Antwort
        :type: object
        :storage_location: creative_works
        :delete: true
        :name: Antwort
        :validations:
          :maxLength: 1
        :editor:
          :type: embeddedObject
          :sorting: 6
      :suggested_answer:
        :label: Falsche Antwort
        :type: object
        :storage_location: creative_works
        :delete: true
        :name: Antwort
        :editor:
          :type: embeddedObject
          :sorting: 7
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Frage"
      # mixin: meta_data
      :creator:
        :label: Ersteller
        :type: embeddedLink
        :type_name: users
        :storage_type: string
        :storage_location: metadata
      :date_created:
        :label: Erstellungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time
      :date_modified:
        :label: Änderungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time

- :data:
    :name: Antwort
    :type: object
    :content_type: embedded
    :permissions:
      :read_write: true
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :text:
        :label: Antwort
        :type: string
        :storage_type: text
        :storage_location: content
        :validations:
          :minLength: 1
        :editor:
          :type: quillEditor
          :sorting: 4
          :options:
            :data-size: basic
            :data-validate: text
        :label: Bild
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: array
        :storage_location: metadata
        :validations:
          :max: 1
        :editor:
          :sorting: 5
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Antwort"
      # mixin: meta_data
      :creator:
        :label: Ersteller
        :type: embeddedLink
        :type_name: users
        :storage_type: string
        :storage_location: metadata
      :date_created:
        :label: Erstellungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time
      :date_modified:
        :label: Änderungsdatum
        :type: string
        :storage_type: string
        :storage_location: metadata
        :validations:
          :format: date_time
