---
- :data:
    :name: SocialMediaPosting
    :type: object
    :content_type: entity
    :releasable: true
    :permissions:
      :read_write: true
    :boost: 100.0
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :headline:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :options:
            :data-validate: text
      :validity_period:
        :type: mixin
        :name: validity_period
      :text:
        :label: Text
        :type: string
        :storage_type: text
        :storage_location: content
        :search: true
        :editor:
          :type: quillEditor
          :options:
            :data-size: basic
      :image:
        :label: Bilder
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: array
        :storage_location: metadata
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
#      :video:
#        :label: Videos
#        :type: embeddedLinkArray
#        :type_name: creative_works
#        :storage_type: array
#        :storage_location: metadata
#        :releasable: true
#        :editor:
#          :options:
#            :data-validate: media
#            :data-type: video
      :url:
        :label: Link
        :type: string
        :storage_type: string
        :storage_location: content
        :search: true
        :validations:
          :format: url
        :editor:
          :type: input
      :content_location:
        :label: Ort
        :type: object
        :storage_location: places
        :name: Örtlichkeit
        :delete: false
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: object
            :data-type: place
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Social Media Posting"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :publication_schedule:
        :label: Geplante Publikation
        :type: object
        :storage_location: creative_works
        :delete: true
        :name: Publikations-Plan
        :validations:
          :classifications: no_conflicts
        :editor:
          :type: embeddedObject
