---
- :data:
    :name: Website
    :type: object
    :schema_type: CreativeWork
    :content_type: embedded
    :api:
      :type: Website
    :properties:
      :id:
        :label: id
        :type: key
      :url:
        :label: Link
        :type: string
        :storage_location: translated_value
        :validations:
          :min: 1
          :format: url
      :link_name:
        :label: Linktitel
        :type: string
        :storage_location: translated_value
        :validations:
          :min: 1
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
        :api:
          :name: name
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Website"
