---
- :data:
    :name: Zeitleiste
    :type: object
    :content_type: entity
    :releasable: true
    :permissions:
      :read_write: true
    :boost: 100.0
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :headline:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: column
        :search: true
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :options:
            :data-validate: text
      :validity_period:
        :type: mixin
        :name: validity_period
      :description:
        :label: Teasertext
        :type: string
        :storage_type: text
        :storage_location: column
        :search: true
        :editor:
          :type: quillEditor
          :options:
            :data-size: full
      :timeline_item:
        :label: Eintrag
        :type: object
        :storage_location: creative_works
        :delete: true
        :name: Zeitleiste-Eintrag
        :editor:
          :type: embeddedObject
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Zeitleiste"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties

- :data:
    :name: Zeitleiste-Eintrag
    :type: object
    :content_type: embedded
    :permissions:
      :read_write: true
    :properties:
      :id:
        :label: id
        :type: string
        :storage_type: string
        :storage_location: key
        :validations:
          :format: uuid
      :headline:
        :label: Titel
        :type: string
        :storage_type: string
        :storage_location: column
        :validations:
          :minLength: 1
        :editor:
          :type: input
          :options:
            :data-validate: text
      :temporal_coverage:
        :label: Zeitraum
        :type: object
        :storage_location: metadata
        :validations:
          :daterange:
            :from: valid_from
            :to: valid_until
        :editor:
          :options:
            :class: daterange
        :properties:
          :valid_from:
            :label: Zeitraum
            :type: string
            :storage_type: string
            :storage_location: metadata
            :validations:
              :format: date
            :editor:
              :type: datetime
              :options:
                :data-type: datepicker
                :data-validate: daterange
                :placeholder: "tt.mm.jjjj --:--"
          :valid_until:
            :label: bis
            :type: string
            :storage_type: string
            :storage_location: metadata
            :validations:
              :format: date
            :editor:
              :type: datetime
              :options:
                :data-type: datepicker
                :data-validate: daterange
                :placeholder: "tt.mm.jjjj --:--"
      :description:
        :label: Teasertext
        :type: string
        :storage_type: text
        :storage_location: column
        :editor:
          :type: quillEditor
          :options:
            :data-size: full
      :image:
        :label: Bild
        :type: embeddedLinkArray
        :type_name: creative_works
        :storage_type: array
        :storage_location: metadata
        :validations:
          :max: 1
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: media
            :data-type: image
      :content_location:
        :label: Ort
        :type: object
        :storage_location: places
        :name: Örtlichkeit
        :delete: false
        :editor:
          :type: objectBrowser
          :options:
            :data-validate: object
            :data-type: place
      :data_type:
        :label: Inhaltstype
        :type: classificationTreeLabel
        :type_name: Inhaltstypen
        :storage_location: classification_relation
        :default_value: "Zeitleiste-Eintrag"
      :meta_data:
        :type: mixin
        :name: meta_data