---
- :data:
    :name: Örtlichkeit
    :type: object
    :schema_type: Place
    :content_type: entity
    :translatable: true
    :boost: 10.0
    :features:
      :geocode:
        :allowed: true
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :postal_address:
        :type: mixin
        :name: postal_address
      :geo:
        :type: mixin
        :name: geo
      :contact_info:
        :type: mixin
        :name: contact_info
      :description:
        :label: Beschreibung
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :text:
        :label: Text
        :type: string
        :storage_location: translated_value
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :primary_image:
        :label: Hauptbild
        :type: linked
        :template_name: Bild
        :validations:
          :max: 1
      :image:
        :label: Bilder
        :type: linked
        :template_name: Bild
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Örtlichkeit"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
