---
- :data:
    :name: content_classifications
    :type: mixin
    :properties:
      :tags:
        :label: Tags
        :type: classificationTreeLabel
        :type_name: Tags
        :storage_location: classification_relation
        :editor:
          :type: classificationSelector
      :output_channel:
        :label: Ausgabekanal
        :type: classificationTreeLabel
        :type_name: Ausgabekanäle
        :storage_location: classification_relation
        :editor:
          :type: classificationSelector