---
- :data:
    :name: content_classifications
    :type: mixin
    :properties:
      :topic:
        :label: Themenbereiche
        :type: classificationTreeLabel
        :type_name: Themenbereiche
        :storage_location: classification_relation
        :editor:
          :type: classificationSelector
      :output_channel:
        :label: Ausgabekanal
        :type: classificationTreeLabel
        :type_name: Ausgabekanäle
        :storage_location: classification_relation
        :editor:
          :type: classificationSelector