---
- :data:
    :name: EventOverlay
    :type: object
    :schema_type: Event
    :content_type: embedded
    :translatable: true
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Titel
        :type: string
        :storage_location: column
      :event_period:
        :label: Veranstaltungszeitraum
        :type: object
        :storage_location: value
        :validations:
          :daterange:
            :from: start_date
            :to: end_date
        :ui:
          :edit:
            :type: daterange
        :properties:
          :start_date:
            :label: Startzeitpunkt
            :type: datetime
            :storage_location: column
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: datetime
                :options:
                  :data-validate: daterange
                  :placeholder: "tt.mm.jjjj --:--"
          :end_date:
            :label: Endzeitpunkt
            :type: datetime
            :storage_location: column
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: datetime
                :options:
                  :data-validate: daterange
                  :placeholder: "tt.mm.jjjj --:--"
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :image:
        :label: Bilder
        :type: linked
        :linked_table: creative_works
        :template_name: Bild
      :url:
        :label: URL
        :type: string
        :storage_location: translated_value
        :validations:
          :format: url
        :api:
          :name: sameAs
      :content_location:
        :label: Veranstaltungsort
        :type: linked
        :linked_table: things
        :template_name: Örtlichkeit
        :validations:
          :max: 1
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Overlay"
