# author: rainer@pixelpoint.at
inherit_from: vendor/gems/data-cycle-core/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 5.2.3
  DisplayCopNames: true
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'cache/**/*'
    - 'vendor/gems/data-cycle-core/cache/**/*'
    - 'vendor/gems/data-cycle-core/node_modules/**/*'
    - 'vendor/gems/data-cycle-core/tmp/**/*'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
