########################################################################
######################### DOCKER setup for DC
stages:
  - build
  - check
  - test
  - build-docker
  - deploy

before_script:
  - gem install bundler
  - bundle config set --local path 'cache/bundler'
  - bundle install

  - dpkg-reconfigure -f noninteractive tzdata
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - export RUBYOPT="-W:no-deprecated -W:no-experimental"

########################################################################
######################### Branch Configuration
.docker_ci_config: &docker_ci
  only:
    - master
  tags:
    - dc-docker

########################################################################
######################### Master / Production - Systems
build_caches:
  <<: *docker_ci
  extends: .build_caches_config

code_validation:
  <<: *docker_ci
  extends: .code_validation_config

build_docker_job:
  <<: *docker_ci
  extends: .build_docker_config

deploy_docker_job:
  <<: *docker_ci
  extends: .deploy_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT
    url: $DOCKER_URL
    on_stop: stop_docker_job

stop_docker_job:
  <<: *docker_ci
  extends: .stop_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT
    action: stop

restart_docker_job:
  <<: *docker_ci
  extends: .restart_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT
    url: $DOCKER_URL

post_deploy_docker_job:
  <<: *docker_ci
  extends: .post_deploy_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT
    url: $DOCKER_URL
