########################################################################
######################### Development / Staging - Systems
.master_ci_config: &master_ci
  only:
    - master
  tags:
    - dc-master

.development_ci_config: &development_ci
  only:
    - develop
  tags:
    - dc-develop

########################################################################
######################### Master / Production - Systems
# Enable for local rails test
rails_test:
  <<: *master_ci
  extends: .rails_test_config

########################################################################
######################### Development / Staging - Systems
# Enable for local rails test
rails_test_develop:
  <<: *development_ci
  extends: .rails_test_config
