image: git.pixelpoint.biz:5050/data-cycle/data-cycle-core/base:latest

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 'password'
  POSTGRES_HOST: postgres
  POSTGRES_DB: data-cycle-base_test
  POSTGRES_PORT: '5432'
  MONGODB_HOST: mongodb
  RAILS_ENV: test
  TZ: Europe/Vienna
  PRODUCTION_URL: ''

stages:
  - build
  - test
  - check
  - deploy

before_script:
  # uncomment for local testing
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  # uncomment for local testing END
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan git.pixelpoint.biz >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

  - rm -Rf vendor/gems/data-cycle-core
  - git submodule sync --recursive
  - git submodule update --init --recursive --force

  - gem install bundler
  - bundle config set --local path 'cache/bundler'
  - bundle install

  - dpkg-reconfigure -f noninteractive tzdata
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - export RUBYOPT="-W:no-deprecated -W:no-experimental"

cache:
  key: application-cache
  untracked: false
  paths:
    - cache/bundler
    - node_modules
    - public/assets
    - tmp/cache/vite
    # - lib/assets
    # Enable for local rails test
    # - vendor/gems/data-cycle-core/node_modules
    # - vendor/gems/data-cycle-core/lib/assets

services:
  - name: 'git.pixelpoint.biz:5050/data-cycle/data-cycle-core/postgres:latest'
    alias: postgres
    command: ['postgres']
  - name: mvertes/alpine-mongo:4.0.6-1
    alias: mongodb

########################################################################
######################### Job Configuration HiddenFields
.job_cache_config:
  cache:
    key: application-cache
    paths:
      - cache/bundler
      - node_modules
      - public/assets
      - tmp/cache/vite
      # - lib/assets
      # Enable for local rails test
      # - vendor/gems/data-cycle-core/node_modules
      # - vendor/gems/data-cycle-core/lib/assets
    policy: pull

.build_caches_config:
  stage: build
  script:
    - gem install bundler
    - bundle config set --local path 'cache/bundler'
    - bundle install
    - cd $CI_PROJECT_DIR
    - yarn --ignore-scripts
    - yarn upgrade --ignore-scripts data-cycle-core

.code_validation_config:
  extends: .job_cache_config
  stage: check
  script:
    - bundle exec bundle-audit update
    - bundle exec bundle audit check --ignore CVE-2021-21288 CVE-2021-21305
    - bundle exec brakeman
    - bundle exec rubocop --format fuubar
    - bundle exec fasterer

.deploy_config:
  extends: .job_cache_config
  stage: deploy
  cache:
    policy: pull-push
  script:
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - bundle exec cap $CI_COMMIT_REF_NAME deploy
  allow_failure: false

########################################################################
######################### Branch Configuration
.master_ci_config: &master_ci
  only:
    - master
  tags:
    - dc-master

########################################################################
######################### Master / Production - Systems
build_caches:
  <<: *master_ci
  extends: .build_caches_config

code_validation:
  <<: *master_ci
  extends: .code_validation_config

deploy:
  <<: *master_ci
  extends: .deploy_config
  tags:
    - dc-deploy
  environment:
    name: production
    url: $PRODUCTION_URL
  when: manual
