########################################################################
######################### DOCKER setup for DC
stages:
  - build
  - check
  - test
  - build-docker
  - deploy
  - post_deploy

before_script:
  - gem install bundler
  - bundle config set --local path 'cache/bundler'
  - bundle install
  - export RUBYOPT="-W:no-deprecated -W:no-experimental"

########################################################################
######################### Branch Configuration
.docker_develop_ci_config: &docker_develop_ci
  only:
    - develop
  tags:
    - dc-docker

########################################################################
######################### Job configuration
build_caches_develop:
  <<: *docker_develop_ci
  extends: .build_caches_config

code_validation_develop:
  <<: *docker_develop_ci
  extends: .code_validation_config

build_docker_job_develop:
  <<: *docker_develop_ci
  extends: .build_docker_config

deploy_docker_job_develop:
  <<: *docker_develop_ci
  extends: .deploy_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT_DEVELOPMENT
    url: $DOCKER_URL_DEVELOPMENT
    on_stop: stop_docker_job_develop

stop_docker_job_develop:
  <<: *docker_develop_ci
  extends: .stop_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT_DEVELOPMENT
    action: stop

restart_docker_job_develop:
  <<: *docker_develop_ci
  extends: .restart_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT_DEVELOPMENT
    url: $DOCKER_URL_DEVELOPMENT

post_deploy_docker_job_develop:
  <<: *docker_develop_ci
  extends: .post_deploy_docker_config
  environment:
    name: $GITLAB_ENVIRONMENT_DEVELOPMENT
    url: $DOCKER_URL_DEVELOPMENT

