---
- :data:
    :name: Teilstrecke
    :type: object
    :schema_type: Place
    :content_type: entity
    :boost: 100.0
    :features:
      :translatable:
        :allowed: true
      :download:
        :allowed: true
      :overlay:
        :allowed: true
      :serialize:
        :allowed: true
        :serializers:
          :xml: true
          :json: true
          :gpx: true
          :indesign: true
    :properties:
      :id:
        :label: id
        :type: key
      :name:
        :label: Titel
        :type: string
        :storage_location: column
        :search: true
        :validations:
          :required: true
        :ui:
          :show:
            :content_area: none
        :api:
          :minimal: true
      :internal_name:
        :label: Interner Name
        :type: string
        :storage_location: column
        :search: true
        :api:
          :disabled: true
      :owner:
        :label: Besitzer
        :type: classification
        :tree_label: Besitzer
        :validations:
          :required: true
        :ui:
          :show:
            :content_area: header
      :referencetype:
        :label: Radroutentyp
        :type: classification
        :tree_label: Radroutentyp
        :validations:
          :required: true
        :ui:
          :show:
            :content_area: header
      :orgcode:
        :label: Organisationscode
        :type: classification
        :tree_label: Organisationscode
        :ui:
          :show:
            :content_area: header
      :minortyperef:
        :label: Ergänzungstyp
        :type: classification
        :tree_label: Ergänzungstyp
        :ui:
          :show:
            :content_area: header
      :sustainer:
        :label: Erhalter
        :type: classification
        :tree_label: Erhalter
        :ui:
          :show:
            :content_area: header
      :atroute:
        :label: Österreichische Radrouten
        :type: classification
        :tree_label: Österreichische Radrouten
        :ui:
          :show:
            :content_area: header
      :eurovelo:
        :label: EURO Velo Radrouten
        :type: classification
        :tree_label: EURO Velo Radrouten
        :ui:
          :show:
            :content_area: header
      :bikecomfort:
        :label: Schwierigkeitsgrad
        :type: classification
        :tree_label: Schwierigkeitsgrad
        :ui:
          :show:
            :content_area: header
      :bikeroutestate:
        :label: Radroutenstatus
        :type: classification
        :tree_label: Radroutenstatus
        :ui:
          :show:
            :content_area: header
      :signage:
        :label: Beschilderung
        :type: classification
        :tree_label: Beschilderung
        :ui:
          :show:
            :content_area: header
      :bikeroute:
        :label: Radroutenausprägung
        :type: classification
        :tree_label: Radroutenausprägung
        :ui:
          :show:
            :content_area: header
      :geoname_route:
        :label: Bestehende Route
        :type: linked
        :template_name: Route
        :validations:
          :max: 1
        :ui:
          :edit:
            :disabled: true
          :show:
            :disabled: true
      :geoname_name:
        :label: Name der Radroute
        :type: string
        :storage_location: value
        :default_value:
          :module: DataCycleCore::Utility::DefaultValue::String
          :method: linked_gip_route_attribute
          :linked_attribute: name
          :parameters:
            :linked: geoname_route
      :geoname_number:
        :label: Nummer der Radroute
        :type: string
        :storage_location: value
        :default_value:
          :module: DataCycleCore::Utility::DefaultValue::String
          :method: linked_gip_route_attribute
          :linked_attribute: route_number
          :parameters:
            :linked: geoname_route
      :line:
        :label: Teilstrecke
        :storage_location: column
        :type: geographic
        :ui:
          :edit:
            :disabled: false
            :type: LineString
            :options:
              :data_upload: true
      :linked_data:
        :type: mixin
        :name: linked_data
      :subject_of:
        :label: Thema von
        :type: linked
        :inverse_of: about
        :link_direction: inverse
        :global: true
      :data_type:
        :label: Inhaltstyp
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: 'Teilstrecke'
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties
