---
- :data:
    :name: Biografie
    :type: object
    :content_type: entity
    :boost: 100.0
    :features:
      :publication_schedule: ['publication_schedule']
      :releasable: true
    :properties:
      :id:
        :label: id
        :type: key
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :text:
        :label: Fließtext
        :type: string
        :storage_location: translated_value
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: full
      :image:
        :label: Bilder
        :type: linked
        :linked_table: creative_works
        :template_name: Bild
      :about:
        :label: Person
        :type: linked
        :linked_table: persons
        :template_name: Person
        :validations:
          :max: 1
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Biografie"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :publication_schedule:
        :type: mixin
        :name: publication_schedule
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties