---
- :data:
    :name: Zeitleiste
    :type: object
    :content_type: entity
    :boost: 100.0
    :features:
      :releasable:
        :allowed: true
    :properties:
      :id:
        :label: id
        :type: key
      :release_status:
        :type: mixin
        :name: releasable
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :timeline_item:
        :label: Eintrag
        :type: embedded
        :linked_table: creative_works
        :template_name: Zeitleiste-Eintrag
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Zeitleiste"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :publication_schedule:
        :type: mixin
        :name: publication_schedule
      :meta_data:
        :type: mixin
        :name: meta_data
      :additional_properties:
        :type: mixin
        :name: additional_properties

- :data:
    :name: Zeitleiste-Eintrag
    :type: object
    :content_type: embedded
    :properties:
      :id:
        :label: id
        :type: key
      :headline:
        :label: Titel
        :type: string
        :storage_location: column
        :search: true
        :validations:
          :min: 1
      :temporal_coverage:
        :label: Zeitraum
        :type: object
        :storage_location: value
        :validations:
          :daterange:
            :from: valid_from
            :to: valid_until
        :ui:
          :edit:
            :type: daterange
        :properties:
          :valid_from:
            :label: Zeitraum
            :type: datetime
            :storage_location: value
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: datetime
                :options:
                  :data-validate: daterange
                  :placeholder: "tt.mm.jjjj --:--"
          :valid_until:
            :label: bis
            :type: datetime
            :storage_location: value
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: datetime
                :options:
                  :data-validate: daterange
                  :placeholder: "tt.mm.jjjj --:--"
      :description:
        :label: Teasertext
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :image:
        :label: Bilder
        :type: linked
        :linked_table: creative_works
        :template_name: Bild
        :validations:
          :max: 1
      :content_location:
        :label: Ort
        :type: linked
        :linked_table: places
        :template_name: Örtlichkeit
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Zeitleiste-Eintrag"
      :meta_data:
        :type: mixin
        :name: meta_data
