# frozen_string_literal: true

module DataCycleCore
  module Generic
    module DestinationOne
      module Transformations
        def self.t(*args)
          DataCycleCore::Generic::DestinationOne::TransformationFunctions[*args]
        end

        def self.to_poi(external_source_id)
          t(:add_field, 'external_key', ->(s) { "destination.one - #{s.dig('type')} - #{s.dig('id')}" })
          .>> t(:add_info, external_source_id)
          .>> t(:add_opening_hours_specification, external_source_id)
          .>> t(:add_field, 'name', ->(s) { s.dig('title') })
          .>> t(:add_field, 'date_created', ->(s) { s.dig('created')&.in_time_zone })
          .>> t(:add_field, 'date_modified', ->(s) { s.dig('changed')&.in_time_zone })
          .>> t(:add_field, 'latitude', ->(s) { s.dig('geo', 'main', 'latitude') })
          .>> t(:add_field, 'longitude', ->(s) { s.dig('geo', 'main', 'longitude') })
          .>> t(:location)
          .>> t(:add_field, 'street_address', ->(s) { s.dig('street').presence })
          .>> t(:add_field, 'postal_code', ->(s) { s.dig('zip').presence })
          .>> t(:add_field, 'address_locality', ->(s) { s.dig('city').presence })
          .>> t(:add_field, 'address_country', ->(s) { s.dig('country').presence })
          .>> t(:nest, 'address', ['street_address', 'postal_code', 'address_locality', 'address_country'])
          .>> t(:add_field, 'telephone', ->(s) { s.dig('phone').presence })
          .>> t(:add_field, 'fax_number', ->(s) { s.dig('fax').presence })
          .>> t(:add_field, 'email', ->(s) { s.dig('email').presence })
          .>> t(:add_field, 'url', ->(s) { s.dig('web').presence })
          .>> t(:nest, 'contact_info', ['telephone', 'fax_number', 'email', 'url'])
          .>> t(:add_links, 'do_categories', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['categories'])&.map { |i| "destination.one - #{s.dig('type')} - Category - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_categories') })
          .>> t(:add_links, 'do_areas', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['areas'])&.map { |i| "destination.one - Area - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_areas') })
          .>> t(:add_links, 'do_keywords', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['keywords'])&.map { |i| "destination.one - #{s.dig('type')} - Keyword - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_keywords') })
          .>> t(:add_links, 'do_features', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['features'])&.map { |i| "destination.one - Feature - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_features') })
          .>> t(:add_links, 'do_source', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s.dig('source', 'value'))&.map { |i| "destination.one - Source - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_source') })
          .>> t(:add_links, 'image', DataCycleCore::Thing, external_source_id, ->(s) { Array.wrap(s['media_objects'])&.map { |i| i['url'] } })
          .>> t(:add_ccc, ->(s) { s.dig('attributes')&.detect { |i| i['key'] == 'license' }&.dig('value') })
          .>> t(:reject_keys, ['id', 'geo', 'source', 'categories', 'areas', 'keywords', 'features', 'source'])
        end

        def self.to_tour(external_source_id)
          t(:add_field, 'external_key', ->(s) { "destination.one - #{s.dig('type')} - #{s.dig('id')}" })
          .>> t(:add_info, external_source_id)
          .>> t(:add_opening_hours_specification, external_source_id)
          .>> t(:add_field, 'name', ->(s) { s.dig('title') })
          .>> t(:add_field, 'date_created', ->(s) { s.dig('created')&.in_time_zone })
          .>> t(:add_field, 'date_modified', ->(s) { s.dig('changed')&.in_time_zone })
          .>> t(:add_field, 'latitude', ->(s) { s.dig('geo', 'main', 'latitude') })
          .>> t(:add_field, 'longitude', ->(s) { s.dig('geo', 'main', 'longitude') })
          .>> t(:location)
          .>> t(:add_tour, ->(s) { s.dig('geo', 'geometry', 'value') })
          .>> t(:add_field, 'street_address', ->(s) { s.dig('street').presence })
          .>> t(:add_field, 'postal_code', ->(s) { s.dig('zip').presence })
          .>> t(:add_field, 'address_locality', ->(s) { s.dig('city').presence })
          .>> t(:add_field, 'address_country', ->(s) { s.dig('country').presence })
          .>> t(:nest, 'address', ['street_address', 'postal_code', 'address_locality', 'address_country'])
          .>> t(:add_field, 'telephone', ->(s) { s.dig('phone').presence })
          .>> t(:add_field, 'fax_number', ->(s) { s.dig('fax').presence })
          .>> t(:add_field, 'email', ->(s) { s.dig('email').presence })
          .>> t(:add_field, 'url', ->(s) { s.dig('web').presence })
          .>> t(:nest, 'contact_info', ['telephone', 'fax_number', 'email', 'url'])
          .>> t(:rename_keys, { 'elevationMin' => 'min_altitude', 'elevationMax' => 'max_altitude', 'totalAscent' => 'ascent', 'totalDescent' => 'descent' })
          .>> t(:map_value, 'duration', ->(s) { s&.send(:/, 60.0)&.to_i })
          .>> t(:add_links, 'do_categories', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['categories'])&.map { |i| "destination.one - #{s.dig('type')} - Category - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_categories') })
          .>> t(:add_links, 'do_areas', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['areas'])&.map { |i| "destination.one - Area - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_areas') })
          .>> t(:add_links, 'do_keywords', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['keywords'])&.map { |i| "destination.one - #{s.dig('type')} - Keyword - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_keywords') })
          .>> t(:add_links, 'do_features', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['features'])&.map { |i| "destination.one - Feature - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_features') })
          .>> t(:add_links, 'do_source', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s.dig('source', 'value'))&.map { |i| "destination.one - Source - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_source') })
          .>> t(:add_links, 'image', DataCycleCore::Thing, external_source_id, ->(s) { Array.wrap(s['media_objects'])&.map { |i| i['url'] } })
          .>> t(:add_ccc, ->(s) { s.dig('attributes')&.detect { |i| i['key'] == 'license' }&.dig('value') })
          .>> t(:reject_keys, ['id', 'geo', 'source', 'categories', 'areas', 'keywords', 'features', 'source'])
        end

        def self.to_gastro(external_source_id)
          t(:add_field, 'external_key', ->(s) { "destination.one - #{s.dig('type')} - #{s.dig('id')}" })
          .>> t(:add_info, external_source_id)
          .>> t(:add_opening_hours_specification, external_source_id)
          .>> t(:add_dining_hours_specification, external_source_id)
          .>> t(:add_field, 'name', ->(s) { s.dig('title') })
          .>> t(:add_field, 'date_created', ->(s) { s.dig('created')&.in_time_zone })
          .>> t(:add_field, 'date_modified', ->(s) { s.dig('changed')&.in_time_zone })
          .>> t(:add_field, 'latitude', ->(s) { s.dig('geo', 'main', 'latitude') })
          .>> t(:add_field, 'longitude', ->(s) { s.dig('geo', 'main', 'longitude') })
          .>> t(:location)
          .>> t(:add_field, 'street_address', ->(s) { s.dig('street').presence })
          .>> t(:add_field, 'postal_code', ->(s) { s.dig('zip').presence })
          .>> t(:add_field, 'address_locality', ->(s) { s.dig('city').presence })
          .>> t(:add_field, 'address_country', ->(s) { s.dig('country').presence })
          .>> t(:nest, 'address', ['street_address', 'postal_code', 'address_locality', 'address_country'])
          .>> t(:add_field, 'telephone', ->(s) { s.dig('phone').presence })
          .>> t(:add_field, 'fax_number', ->(s) { s.dig('fax').presence })
          .>> t(:add_field, 'email', ->(s) { s.dig('email').presence })
          .>> t(:add_field, 'url', ->(s) { s.dig('web').presence })
          .>> t(:nest, 'contact_info', ['telephone', 'fax_number', 'email', 'url'])
          .>> t(:add_links, 'do_categories', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['categories'])&.map { |i| "destination.one - #{s.dig('type')} - Category - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_categories') })
          .>> t(:add_links, 'do_areas', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['areas'])&.map { |i| "destination.one - Area - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_areas') })
          .>> t(:add_links, 'do_keywords', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['keywords'])&.map { |i| "destination.one - #{s.dig('type')} - Keyword - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_keywords') })
          .>> t(:add_links, 'do_features', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['features'])&.map { |i| "destination.one - Feature - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_features') })
          .>> t(:add_links, 'do_source', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s.dig('source', 'value'))&.map { |i| "destination.one - Source - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_source') })
          .>> t(:add_links, 'do_cuisine_types', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s.dig('cuisine_types'))&.map { |i| "destination.one - Cuisine Type - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_cuisine_types') })
          .>> t(:add_links, 'image', DataCycleCore::Thing, external_source_id, ->(s) { Array.wrap(s['media_objects'])&.map { |i| i['url'] } })
          .>> t(:add_ccc, ->(s) { s.dig('attributes')&.detect { |i| i['key'] == 'license' }&.dig('value') })
          .>> t(:reject_keys, ['id', 'geo', 'source', 'categories', 'areas', 'keywords', 'features', 'source'])
        end

        def self.to_hotel(external_source_id)
          t(:add_field, 'external_key', ->(s) { "destination.one - #{s.dig('type')} - #{s.dig('id')}" })
          .>> t(:add_field, 'bookable', ->(_) { true })
          .>> t(:add_info, external_source_id)
          .>> t(:add_field, 'name', ->(s) { s.dig('title') })
          .>> t(:add_field, 'date_created', ->(s) { s.dig('created')&.in_time_zone })
          .>> t(:add_field, 'date_modified', ->(s) { s.dig('changed')&.in_time_zone })
          .>> t(:add_field, 'latitude', ->(s) { s.dig('geo', 'main', 'latitude') })
          .>> t(:add_field, 'longitude', ->(s) { s.dig('geo', 'main', 'longitude') })
          .>> t(:location)
          .>> t(:add_field, 'street_address', ->(s) { s.dig('street').presence })
          .>> t(:add_field, 'postal_code', ->(s) { s.dig('zip').presence })
          .>> t(:add_field, 'address_locality', ->(s) { s.dig('city').presence })
          .>> t(:add_field, 'address_country', ->(s) { s.dig('country').presence })
          .>> t(:nest, 'address', ['street_address', 'postal_code', 'address_locality', 'address_country'])
          .>> t(:add_field, 'telephone', ->(s) { s.dig('phone').presence })
          .>> t(:add_field, 'fax_number', ->(s) { s.dig('fax').presence })
          .>> t(:add_field, 'email', ->(s) { s.dig('email').presence })
          .>> t(:add_field, 'url', ->(s) { s.dig('web').presence })
          .>> t(:nest, 'contact_info', ['telephone', 'fax_number', 'email', 'url'])
          .>> t(:add_field, 'number_of_rooms', ->(s) { Array.wrap(s.dig('numbers')).detect { |i| i['type'] == 'CountRooms' }&.send(:[], 'value') })
          .>> t(:add_field, 'total_number_of_beds', ->(s) { Array.wrap(s.dig('numbers')).detect { |i| i['type'] == 'CountBeds' }&.send(:[], 'value') })
          .>> t(:add_field, 'price_range', ->(s) { Array.wrap(s.dig('numbers')).detect { |i| i['type'] == 'MinPrice' }&.tap { |i| i['value'] = "ab #{i['value']} €" }&.send(:[], 'value') })
          .>> t(:add_links, 'do_categories', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['categories'])&.map { |i| "destination.one - #{s.dig('type')} - Category - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_categories') })
          .>> t(:add_links, 'do_areas', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['areas'])&.map { |i| "destination.one - Area - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_areas') })
          .>> t(:add_links, 'do_keywords', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['keywords'])&.map { |i| "destination.one - #{s.dig('type')} - Keyword - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_keywords') })
          .>> t(:add_links, 'do_features', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['features'])&.map { |i| "destination.one - Feature - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_features') })
          .>> t(:add_links, 'do_source', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s.dig('source', 'value'))&.map { |i| "destination.one - Source - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_source') })
          .>> t(:add_links, 'do_payment', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s.dig('payment'))&.map { |i| "destination.one - Payment - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_payment') })
          .>> t(:add_links, 'image', DataCycleCore::Thing, external_source_id, ->(s) { Array.wrap(s['media_objects'])&.map { |i| i['url'] } })
          .>> t(:add_ccc, ->(s) { s.dig('attributes')&.detect { |i| i['key'] == 'license' }&.dig('value') })
          .>> t(:reject_keys, ['id', 'geo', 'source', 'categories', 'areas', 'keywords', 'features', 'source'])
        end

        def self.to_event(external_source_id)
          t(:add_field, 'external_key', ->(s) { "destination.one - #{s.dig('type')} - #{s.dig('id')}" })
          .>> t(:add_info, external_source_id)
          .>> t(:add_event_schedule, external_source_id)
          .>> t(:add_field, 'name', ->(s) { s.dig('title') })
          .>> t(:add_field, 'date_created', ->(s) { s.dig('created')&.in_time_zone })
          .>> t(:add_field, 'date_modified', ->(s) { s.dig('changed')&.in_time_zone })
          .>> t(:add_links, 'do_categories', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['categories'])&.map { |i| "destination.one - #{s.dig('type')} - Category - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_categories') })
          .>> t(:add_links, 'do_areas', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['areas'])&.map { |i| "destination.one - Area - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_areas') })
          .>> t(:add_links, 'do_keywords', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['keywords'])&.map { |i| "destination.one - #{s.dig('type')} - Keyword - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_keywords') })
          .>> t(:add_links, 'do_features', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s['features'])&.map { |i| "destination.one - Feature - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_features') })
          .>> t(:add_links, 'do_source', DataCycleCore::Classification, external_source_id, ->(s) { Array.wrap(s.dig('source', 'value'))&.map { |i| "destination.one - Source - #{i}" } })
          .>> t(:universal_classifications, ->(s) { s.dig('do_source') })
          .>> t(:add_links, 'image', DataCycleCore::Thing, external_source_id, ->(s) { Array.wrap(s['media_objects'])&.map { |i| i['url'] } })
          .>> t(:add_links, 'content_location', DataCycleCore::Thing, external_source_id, ->(s) { Array.wrap("destination.one - Event Content Location - #{s.dig('id')}") })
          .>> t(:add_links, 'organizer', DataCycleCore::Thing, external_source_id, ->(s) { Array.wrap("destination.one - Event Organizer - #{s.dig('id')}") })
          .>> t(:add_ccc, ->(s) { s.dig('attributes')&.detect { |i| i['key'] == 'license' }&.dig('value') })
          .>> t(:reject_keys, ['id', 'geo', 'source', 'categories', 'areas', 'keywords', 'features'])
        end

        def self.to_content_location
          t(:add_field, 'external_key', ->(s) { "destination.one - Event Content Location - #{s.dig('id')}" })
          .>> t(:add_field, 'latitude', ->(s) { s.dig('geo', 'main', 'latitude') })
          .>> t(:add_field, 'longitude', ->(s) { s.dig('geo', 'main', 'longitude') })
          .>> t(:location)
          .>> t(:add_field, 'street_address', ->(s) { s.dig('street').presence })
          .>> t(:add_field, 'postal_code', ->(s) { s.dig('zip').presence })
          .>> t(:add_field, 'address_locality', ->(s) { s.dig('city').presence })
          .>> t(:add_field, 'address_country', ->(s) { s.dig('country').presence })
          .>> t(:nest, 'address', ['street_address', 'postal_code', 'address_locality', 'address_country'])
          .>> t(:add_field, 'telephone', ->(s) { s.dig('phone').presence })
          .>> t(:add_field, 'fax_number', ->(s) { s.dig('fax').presence })
          .>> t(:add_field, 'email', ->(s) { s.dig('email').presence })
          .>> t(:add_field, 'url', ->(s) { s.dig('web').presence })
          .>> t(:nest, 'contact_info', ['telephone', 'fax_number', 'email', 'url'])
          .>> t(:reject_keys, ['id', 'geo', 'source', 'categories', 'areas', 'keywords', 'features', 'media_objects'])
        end

        def self.to_organizer
          t(:add_field, 'external_key', ->(s) { "destination.one - Event Organizer - #{s.dig('id')}" })
          .>> t(:add_field, 'latitude', ->(s) { s.dig('geo', 'main', 'latitude') })
          .>> t(:add_field, 'longitude', ->(s) { s.dig('geo', 'main', 'longitude') })
          .>> t(:location)
          .>> t(:add_field, 'street_address', ->(s) { s.dig('street').presence })
          .>> t(:add_field, 'postal_code', ->(s) { s.dig('zip').presence })
          .>> t(:add_field, 'address_locality', ->(s) { s.dig('city').presence })
          .>> t(:add_field, 'address_country', ->(s) { s.dig('country').presence })
          .>> t(:nest, 'address', ['street_address', 'postal_code', 'address_locality', 'address_country'])
          .>> t(:add_field, 'telephone', ->(s) { s.dig('phone').presence })
          .>> t(:add_field, 'fax_number', ->(s) { s.dig('fax').presence })
          .>> t(:add_field, 'email', ->(s) { s.dig('email').presence })
          .>> t(:add_field, 'url', ->(s) { s.dig('web').presence })
          .>> t(:nest, 'contact_info', ['telephone', 'fax_number', 'email', 'url'])
          .>> t(:reject_keys, ['id'])
        end

        def self.to_image
          t(:add_field, 'external_key', ->(s) { s.dig('url') })
          .>> t(:add_field, 'thumbnail_url', ->(s) { s.dig('url') })
          .>> t(:add_field, 'content_url', ->(s) { s.dig('url') })
          .>> t(:add_field, 'name', ->(s) { s.dig('value') })
          .>> t(:add_ccc, ->(s) { s['license'] })
          .>> t(:add_field, 'copyright_notice_override', ->(s) { s['source'] })
          .>> t(:reject_keys, ['author', 'license'])
        end
      end
    end
  end
end
