- Inhaltstypen:
  - $$Asset:
    - $$DataCycle - Bild
    - $$DataCycle - Video
    - $$DataCycle - Datei
    - $$DataCycle - PDF
  - $$Text:
    - $$Artikel

- Geschlecht:
  - Männlich
  - Weiblich

- Wochentage:
  - Montag
  - Dienstag
  - Mittwoch
  - Donnerstag
  - Freitag
  - Samstag
  - Sonntag

- Release-Stati:
  - freigegeben
  - beim Partner
  - in Bearbeitung
  - in Review
  - Draft
  - archiviert

- Tags:

- Ausgabekanäle:

- Rezept-Gänge:

- Rezept-Kategorien:

- POI - Kategorien:
