- Inhaltstypen:
  - $$Text:
    - $$Linktipps
    - $$Quiz
    - $$Angebot
    - $$Biografie
    - $$Interview
    - $$Social Media Posting
    - $$Rezept
# hidden
  - $$Zeitleiste
# embedded
  - $$Angebotszeitraum
  - $$Website
  - $$Zeitleiste-Eintrag
  - $$Frage
  - $$Antwort
# container
  - $$Container