- Inhaltstypen:
  - $$Text:
    - $$Biografie
    - $$Interview
    - $$Quiz
    - $$Rezept
    - $$Social Media Posting
  - $$Zeitleiste
# embedded
  - $$Zeitleiste-Eintrag
  - $$Frage
  - $$Antwort
# container
  - $$Container

- Rezept-Gänge:

- Rezept-Kategorien: