---
- :data:
    :name: validity_period
    :type: mixin
    :properties:
      :validity_period:
        :label: Gültigkeitszeitraum
        :type: object
        :storage_location: value
        :validations:
          :daterange:
            :from: valid_from
            :to: valid_until
        :ui:
          :edit:
            :options:
              :class: daterange
        :properties:
          :valid_from:
            :label: Gültigkeit
            :type: datetime
            :storage_location: value
            :validations:
              :format: date_time
            :ui:
              :edit:
                :options:
                  :data-validate: daterange
                  :placeholder: tt.mm.jjjj
          :valid_until:
            :label: bis
            :type: datetime
            :storage_location: value
            :validations:
              :format: date_time
            :ui:
              :edit:
                :options:
                  :data-validate: daterange
                  :placeholder: tt.mm.jjjj
