---
- :data:
    :name: Event
    :type: object
    :schema_type: Event
    :boost: 100.0
    :content_type: entity
    :features:
      :overlay:
        :allowed: true
      :translatable:
        :allowed: true
    :properties:
      :id:
        :label: id
        :type: key
      :overlay:
        :label: Overlay
        :type: embedded
        :linked_table: things
        :template_name: EventOverlay
        :external: true
        :validations:
          :max: 1
      :title:
        :type: mixin
        :name: title
      :validity_period:
        :type: mixin
        :name: validity_period
      :event_period:
        :label: Veranstaltungszeitraum
        :type: object
        :storage_location: value
        :external: true
        :validations:
          :daterange:
            :from: start_date
            :to: end_date
        :ui:
          :edit:
            :type: daterange
          :show:
            :content_area: header
        :properties:
          :start_date:
            :label: Startzeitpunkt
            :type: datetime
            :storage_location: column
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: datetime
                :options:
                  :data-validate: daterange
                  :placeholder: "tt.mm.jjjj --:--"
          :end_date:
            :label: Endzeitpunkt
            :type: datetime
            :storage_location: column
            :validations:
              :format: date_time
            :ui:
              :edit:
                :type: datetime
                :options:
                  :data-validate: daterange
                  :placeholder: "tt.mm.jjjj --:--"
      :description:
        :label: Beschreibung
        :type: string
        :storage_location: column
        :search: true
        :ui:
          :edit:
            :type: text_editor
            :options:
              :data-size: basic
      :url:
        :label: Inhalt URL
        :type: string
        :storage_location: translated_value
        :external: true
        :validations:
          :format: url
        :api:
          :name: sameAs
      :same_as:
        :label: Link
        :type: string
        :storage_location: translated_value
        :validations:
          :format: url
      :image:
        :label: Bilder
        :type: linked
        :linked_table: things
        :template_name: Bild
      :content_location:
        :label: Veranstaltungsort
        :type: linked
        :linked_table: things
        :template_name: Örtlichkeit
        :validations:
          :max: 1
        :api:
          :name: location
      :sub_event:
        :label: Veranstaltungsdaten
        :type: embedded
        :linked_table: things
        :template_name: SubEvent
      :data_type:
        :label: Inhaltstype
        :type: classification
        :tree_label: Inhaltstypen
        :default_value: "Veranstaltung"
      :content_classifications:
        :type: mixin
        :name: content_classifications
      :meta_data:
        :type: mixin
        :name: meta_data
      :event_db:
        :type: mixin
        :name: event_db
      :v_ticket:
        :type: mixin
        :name: v_ticket
      :additional_properties:
        :type: mixin
        :name: additional_properties
